### ISSUE TITLE
Mapsui.Samples.Forms.Mac: configs are messed up

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1051]
I'm trying to build the sample app `Mapsui.Samples.Forms.Mac` on a MacBook with Visual Studio for Mac (current stable version 8.8.6), but some things are rather strange in this context ...

The only configurations that are buildable for this project are:
- Debug | iPhone
- Release | AnyCPU
- Release | iPhone

Regarding AnyCPU: Why only Release and not Debug? And: Why do the iPhone configs occur in this list at all?

Btw, the two Release configs build and run ok, but `Debug | iPhone` fails with this error:
```
Error MM0009: Error while loading assemblies: /Users/janus/.nuget/packages/harfbuzzsharp/2.6.1.7/runtimes/win-x64/native/libHarfBuzzSharp.dll. (MM0009) (Mapsui.Samples.Forms.Mac)
```

Looking into the project options for `Mapsui.Samples.Forms.Mac`, the only two configurations defined there are:
- Debug | iPhone
- Release | iPhone

Again: Why iPhone? This is supposed to be a MacOS app, right? Looking into their settings, the config called `Debug | iPhone` actually targets x64, while `Release | iPhone` targets AnyCPU, and both of them show x86_64 as supported architecture. So it looks like those two configs are at least misnamed. Also they are inconsistent regarding the target. Plus, the mapping to the solution configs needs adjustment.

**Comment by charlenni** [comment]
I assume, that I have to answer on these questions, because these parts are made by me.

The answer for all above questions is: I didn't know it better. I added the Mac projects to show, that it would be possible to use Mapsui on Mac too. But I didn't look after any configurations. I started one project, and, when it was running, I dropped any further efforts in the Mac part. Meanwhile, I dropped my efforts on this project, because I made so many mistakes.

So, if you find any problems in the Forms part of Mapsui, don't hesitate to correct them ;-)

**Comment by janusw** [comment]
Thanks for the comments, @charlenni. I'll try to clean up the Mac sample project a bit and fix the non-working Debug config.

**Comment by charlenni** [comment]
@janusw That would be great. Thank you.

**Comment by janusw** [comment]
> I added the Mac projects to show, that it would be possible to use Mapsui on Mac too.

Actually it's a very unique feature of the Xamarin framework, that it enables you to target mobile platforms (Android & iOS) as well as desktop platforms (MacOS, Windows & Linux), all with the same code base. That's really kind of neat.

While it may not make too much sense for certain kinds of applications (e.g. ones that make extensive use of all kinds of smartphone sensors that are not available on desktop hardware), map-based apps are an area where this cross-platformness really makes perfect sense. It's great to see that Mapsui supports such a wide range of platforms (even if some corners need a bit more polishing).


> Meanwhile, I dropped my efforts on this project, because I made so many mistakes.

Are you saying you quit working on Mapsui completely? That would be a shame ...

**Comment by janusw** [comment]
Btw, I opened PR #1053 to fix this issue. Reviews welcome :)

**Comment by sailman342** [comment]
Hi, thanks for your efforts :-)

I am also trying to git it working on all these platforms but there are some problems left:

- on wpf buttons are below the map (skiasharp problem)
- on older Macs the map is white (all white)
- forms doesn't support image buttons on mac ...

The solution for getting Mapsui working fine on wpf and macos is to edit Mapsui code to work with canvas instead of GL ...

So you are advised if your encounter something not working :-) good luck

And yes they do an incredible job :-)

**Comment by janusw** [comment]
> Hi, thanks for your efforts :-)

You're welcome :)


> I am also trying to git it working on all these platforms but there are some problems left:
> 
>     * on wpf buttons are below the map (skiasharp problem)

Haven't really tried Mapsui on Windows. My workflow is mostly Mac-based right now.

If you know that it is a SkiaSharp problem, have you reported it there?
 

>     * on older Macs the map is white (all white)

I'm working on a MacBook with Big Sur. Maps show up alright there. How old is "older"?


>     * forms doesn't support image buttons on mac ...

I know that Mac support is not complete for Xamarin.Forms (have encountered some more limitations already).
 
> The solution for getting Mapsui working fine on wpf and macos is to edit Mapsui code to work with canvas instead of GL ...

Not sure what exactly you are talking about here. Maybe you want to elaborate?

Btw, the quickest solution for getting open-source projects to work the way you want them to is to contribute a fix ... ;)

**Comment by sailman342** [comment]
I am not that good yet with Github .... still a lot to learn ... but if I can help I will do :-)

The Skiasharp problem has been reported by Charleni to the Skia team already, but it is not one of their priorities ...

Older likely means no metal ... mine was a mid 2011 iMac

**Comment by janusw** [comment]
> I am not that good yet with Github .... still a lot to learn ... but if I can help I will do :-)

Often a precise report of the problem is alread

> The Skiasharp problem has been reported by Charleni to the Skia team already, but it is not one of their priorities ...
> 
> Older likely means no metal ... mine was a mid 2011 iMac

**Comment by janusw** [comment]
Oops, closed by accident :see_no_evil:

**Comment by janusw** [comment]
> I am not that good yet with Github .... still a lot to learn ... but if I can help I will do :-)

Often a precise report of the problem is a good first step to a fix :)


> Older likely means no metal ... mine was a mid 2011 iMac

OS might be more relevant than HW.


> ```
>     /// </summary>
>     public partial class MapControl : SKCanvasView, IMapControl, IDisposable
>     {
> ```
> 
> in place of SKGL... and this implies one or two minor modifications ...
> 
> Now you know :-)

Thanks for the explanation. You should propose this change in a separate issue (if you haven't done so already) ...

**Comment by sailman342** [comment]
Mac has not been a priority for now, from what I understand, and I don't have a professionnal need so I don't bother the developpers further :-) but it has been reported long time ago

https://github.com/Mapsui/Mapsui/issues/892

If it is of importance for you, when my Mac will be repaired I can make some testing for you :-)

Promised I will learn GitHub :-)

**Comment by charlenni** [comment]
Some comments on this.

If you use SKCanvasView instead of SKGLView, then you use the SW part of Skia instead of the HW part and the performance isn't as good as before.

The white map problem could be a problem with Skia backend and older macs. Perhaps an Apple problem? Metal implementation on older Macs?

The button problem seems to be a problem of Skia and the Forms implementation on WPF. I assume not to see there any progress in next time.

If you really want to support many platforms, then you could create for each platform SkiaSharp supports an own MapControl and use this. Mapsui could be made to only depend on SkiaSharp (what the Forms implementation does). So at the end you don't need Forms to run Mapsui on macOS or Linux.

PS: @janusw It isn't my project, it is the project of Paul. I assume, that he still works on it, even if he didn't do much in the last time.

**Comment by sailman342** [comment]
You could put mapcontrol in a shared project and conditionally include platform-specific code for wpf :-)

I have a version of my project compiling directly with the sources, this allow me to directly see the impacts of the project configuration on Mapsui as well. For instance using XF 5.0 is straightforward, only some changes in using because XF has now a Brush class as Mapsui does :-)

**Comment by janusw** [comment]
> PS: @janusw It isn't my project, it is the project of Paul.

I know it isn't _your_ project, but you're one of the top contributors, obviously. Would you be willing to share your reasons for turning your back on Mapsui?

It _is_ an awesome project 👍

**Comment by pauldendulk** [comment]
Merged the PR
