### ISSUE TITLE
Overlapped polygons area style

### ISSUE THREAD

**Issue by IgorBuchelnikov** [Mapsui/Mapsui#1161]
I've the following polygon definition:

```
var feature = new Feature();
var geometry = new Polygon(new LinearRing(points));
feature.Geometry = geometry;
var style = new SymbolStyle
{
    Fill = new Brush {FillStyle = FillStyle.ForwardDiagonal, Color = fillColor.ToMapsuiColor()},
    Outline = new Pen(color, lineWidth) {PenStyle = PenStyle.Solid}
};

feature.Styles.Add(style);
var geometry = new Polygon(new LinearRing(points));
feature.Styles.Add(style);
```
One polygon can overlap another. I see that the fill of an overlapped area has no difference from the not overlapped area. Can I set fill style for the overlapped area? Maybe a less distance between diagonal lines or a more thickness of diagonal lines.

**Comment by pauldendulk** [comment]
You could make the color of the polygon semi transparent. 

You can also use images to fill a polygon. But I am not sure if you can use them because
1. Not sure of the background of the image can be transparent. 
2. There is a bug in the skia implementation. The image's offset is relative to the whole map, not relative to the geometry.

![mapsui4](https://user-images.githubusercontent.com/963462/126326653-a757e179-a10d-408c-8d00-fc5527054ead.gif)

**Comment by pauldendulk** [comment]
Look for the PolygonTest.cs file.

**Comment by IgorBuchelnikov** [comment]
Thanks, Paul. My end user only accepts diagonal line fill.

**Comment by pauldendulk** [comment]
In that cases fixes are needed in PolygonRenderer.cs.
