### ISSUE TITLE
MemoryProvider graphics not drawn

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#1201]
Since merging the 'Invalidate loop' merge request (https://github.com/Mapsui/Mapsui/pull/1192) I observe MemoryProvider graphics that are not drawn when panning the map (sometimes).  It's most noticeable on Android (Xamarin.Forms app). I've set mapView.UseFling to false to avoid confusion with an earlier similar issue (https://github.com/Mapsui/Mapsui/issues/1183).

To reproduce this issue see sample Mapsui/Sample/Mapsui.Samples.MemoryProvider in branch bug/renderloop_graphics_not_drawn ( https://github.com/Mapsui/Mapsui/tree/bug/renderloop_graphics_not_drawn/Samples/Mapsui.Samples.MemoryProvider/MemoryProvider).

Screenshot: 
<img src="https://user-images.githubusercontent.com/538812/132942126-2e379f84-6d6e-4bdb-9abb-7da4a0011d84.jpg" width="300">

**Comment by charlenni** [comment]
See it on UWP too. This problem hasn't nothing to do with the render loop, but with the new introduced UseFling flag for deactivating the fling behavior.

There is a bug in the UseFling implementation of MapView. It is never set to false, so that you used always fling in your sample. And it is a fling problem. If you add the two lines I suggested in #1198, you get rid of this problem.

A workaround for the UseFling problem could be to use

    _mapView.UseFling = true;
    _mapView.UseFling = false;

So, #1204 should solve the UseFling problem. And #1198 should solve base problem of not redrawing at the end of fling. You need one or the other. Or better both ;-)

**Comment by bertt** [comment]
thanks, I've tested with adding the FlingFinal method from https://github.com/Mapsui/Mapsui/pull/1198 and it seems to solve a lot of problems. I'm now testing with UseFling the default (true).

So I'll close this issue.
