### ISSUE TITLE
Empty map when following UWP Getting Started

### ISSUE THREAD

**Issue by bertt** [Mapsui/Mapsui#1211]
When following the UWP Getting Started (https://github.com/Mapsui/Mapsui/blob/feature/add-getting-started-uwp/docfx/documentation/getting-started-uwp.md) using Mapsui.Native 3.0 rc 2 I get an empty (white) map.

There is a compiler warning about Svg.Skia:

```
Warning		Found conflicts between different versions of "Svg.Skia" that could not be resolved.
There was a conflict between "Svg.Skia, Version=0.5.0.0, Culture=neutral, PublicKeyToken=dafe96fe6c845a74" and "Svg.Skia, Version=0.5.7.1, Culture=neutral, PublicKeyToken=dafe96fe6c845a74".
    "Svg.Skia, Version=0.5.0.0, Culture=neutral, PublicKeyToken=dafe96fe6c845a74" was chosen because it was primary and "Svg.Skia, Version=0.5.7.1, Culture=neutral, PublicKeyToken=dafe96fe6c845a74" was not.
    References which depend on "Svg.Skia, Version=0.5.0.0, Culture=neutral, PublicKeyToken=dafe96fe6c845a74" [C:\Users\btemm\.nuget\packages\svg.skia\0.5.0\lib\netstandard2.0\Svg.Skia.dll].
        C:\Users\btemm\.nuget\packages\svg.skia\0.5.0\lib\netstandard2.0\Svg.Skia.dll
          Project file item includes which caused reference "C:\Users\btemm\.nuget\packages\svg.skia\0.5.0\lib\netstandard2.0\Svg.Skia.dll".
            C:\Users\btemm\.nuget\packages\svg.skia\0.5.0\lib\netstandard2.0\Svg.Skia.dll
    References which depend on "Svg.Skia, Version=0.5.7.1, Culture=neutral, PublicKeyToken=dafe96fe6c845a74" [].
        C:\Users\btemm\.nuget\packages\mapsui\3.0.0-rc.2\lib\netstandard2.0\Mapsui.Rendering.Skia.dll
          Project file item includes which caused reference "C:\Users\btemm\.nuget\packages\mapsui\3.0.0-rc.2\lib\netstandard2.0\Mapsui.Rendering.Skia.dll".
            C:\Users\btemm\.nuget\packages\mapsui\3.0.0-rc.2\lib\netstandard2.0\Mapsui.Rendering.Skia.dll
            C:\Users\btemm\.nuget\packages\mapsui.native\3.0.0-rc.2\lib\uap\Mapsui.UI.Uwp.dll	App11
```

When installing Svg.Skia version 0.5.7.1 the map is correctly displayed.

**Comment by pauldendulk** [comment]
ah! i ran into the same issue a few days ago. This is actually a serious flaw that we had in our documentation for quite a while. Any new user that would try this would move on to something else. If even the gettings started doesn't work ....

The problem is that the user-agent of BruTile is blocked by openstreetmap. Probably someone used BruTile to build a tool to scrape the osm tiles and as a consequence the user-agent got blocked. 

I added a remark to the FAQ (before I knew the problem was also in our getting started). I should add the solution as well.
https://mapsui.com/documentation/faq.html#the-openstreetmap-layer-does-not-show.

## Solution:
Is to use your own user-agent. This is allowed in the new version of BruTile (which is not used by the current released Mapsui). Or you can add the OpenStreetMap utility in Mapsui itself (better).
```csharp
MyMapControl.Map.Layers.Add(OpenStreetMap.CreateTileLayer("your-user-agent"));
```

## More improvements
- Perhaps it is possible to request the name of the main application and use that as part of the user agent.
- We should also update the FAQ with the code to use.

**Comment by bertt** [comment]
I've used the useragent:

```
MapControl.Map.Layers.Add(OpenStreetMap.CreateTileLayer("your-user-agent"));
```

I guess it's something with Svg.Skia dependencies.

**Comment by charlenni** [comment]
From the messages I think it is a SVG.Skia problem as @bertt told. We use packages with two different versions: 0.5.0 and 0.5.7.

**Comment by pauldendulk** [comment]
ohw, I write a long story without even reading the error message 😳

I don't see a 'consolidate' issue with the nugets. So perhaps some of the packages we use has another version as reference. 

Tol solve this you need to add a version Svg.Skia to the head project, but that is not what you want in a tutorial. Perhaps it helps if we add Svg.Skia to the UWP UI project.

**Comment by pauldendulk** [comment]
What if you create this getting started within the Mapsui solution, without a nuget reference?

**Comment by janusw** [comment]
I have opened PR #1215 to fix this ...

**Comment by pauldendulk** [comment]
@bertt Can you confirm that this has been fixed?

**Comment by bertt** [comment]
tested with 3.0.0-rc4 and it works now. Closing issue
