### ISSUE TITLE
FeatureExtensions class Copy() method

### ISSUE THREAD

**Issue by EmaDozer** [Mapsui/Mapsui#1301]
Hello everybody,

I was a little bit confused. I was wondering if the Copy() method in the FeatureExtension class shouldnt be generic?

At the moment, the copied object is always of type Feature:

```
public static IGeometryFeature Copy(this IGeometryFeature original)
{
  return new Feature(original) { Geometry = original.Geometry.Copy() };
}
```

If you want to clone a class that inherited from Feature, the wrong type is returned.

Wouldnt a generic method be more suitable? Something like this:

```
public static T CopyT<T>(this IGeometryFeature original) where T : IGeometryFeature
{
  var copiedFeature = (T)Activator.CreateInstance(typeof(T), original);
  copiedFeature.Geometry = original.Geometry.Copy()
  return copiedFeature;
}
```

Thank you!
Emanuel

**Comment by pauldendulk** [comment]
Had a look at this. As said we are in the middle of a big refactoring. We are about to replace Mapsui.Geometries with NTS library. In the current stage we are limiting the dependency on Mapsui.Geometries. I have been going through all code to  remove Mapsui.Geometries where possible. IGeometryFeature is not a fundamental type, we would like to use IFeature where we can. So I am not  happy solution where IGeometryFeature becomes the parent of an inheritance tree. Instead I would like to have a generic solution for IFeature, but my current conclusion is that I can not find a proper solution for that. This is because every feature has some kind of data field (like Geometry) but this data field not have to inherited from a common interface, it could be anything. In the current master there is IGeometry (with different derived classes), MPoint, MRect, MRaster. These fields all need to be copied.

Then there is also the issue of deep copy and shallow copy. A true deep copy is nearly impossible because the Fields dictionary could contain anything. A shallow copy is not of much use because in most scenario the main thing to copy is the data field.

I have also been thinking about a Copy method in the IFeature interface. Every instance could have its own implementation. In that case we will still have the shallow versus deep copy question. The main thing to copy would be the data field. 

Another option would be to create a IFeature<T> with a method: T Copy<T>(), which would only copy the data field. In combination with the Activator this may help to create a generic solution. Still this solution would be somewhere in between shallow/deep. Not nice. It would allow users to create a copy method for IFeature<T>.

**Comment by pauldendulk** [comment]
Thanks @EmaDozer. I used the Activator you suggested in what I ended up with. I added copy constructors for all feature types. The copy constructor is still half deep/shallow, this is not so nice, but I did not see a better solution. All copy constructor copy the Geometry (or MPoint, MRect, MRaster).

There are now two Copy IFeature extensions. One that works on IFeature but returns an IFeature as well, and a Generic one which returns a specific types. Both have their use cases.

```csharp
public static T Copy<T>(this T original)
{
    return (T)Activator.CreateInstance(typeof(T), original);
}

public static IFeature Copy(this IFeature original)
{
    return (IFeature)Activator.CreateInstance(original.GetType(), original);
}
```
