### ISSUE TITLE
Map is not refreshing correctly

### ISSUE THREAD

**Issue by ndevoecht** [Mapsui/Mapsui#1338]
Hello,

I'm using a really simple map with a custom button "locate user". When pressing this button, the map should display a pin on the user position and center on him. 

Problem is: when pressing the button, the pin start moving from 0,0 to x,y. The map doesn't refresh itself, so I need to press the button multiple times. Each time, the pin moves a bit closer to its real position. How can I make this instantaneous ?

Thanks already!

Mapsui: v2.0.3 (same issue in v3.0.0-alpha.1 - I can't update to v3.0.x because it requires Xamarin.Forms 5)
Mapsui.Forms: v2.0.3
SkiaSharp: v2.80.2
Xamarin.Forms: v4.8.0.1451

[map.zip](https://github.com/Mapsui/Mapsui/files/7474199/map.zip)

**Comment by charlenni** [comment]
I assume, that this is the normal behavior of GPS coordinates on a real device. If you activate the GPS the first time, it tries to deliver a first position. This could be from last time. Then it tries to make the position better and better. If you use an emulator, this shouldn't happen.

The only thing you could do is to activate the GPS very early in your code, so that it has much time to get an accurate position.

**Comment by ndevoecht** [comment]
Hey, thanks for the reply. I forgot to say the position returned by the GPS is correct from the start. The pin is set to the correct location. I just don't understand why it travels.

**Comment by charlenni** [comment]
Sounds like you are using an animated navigator. Try to use `mapView.Navigator.CenterOn(sphericalMercatorCoordinate, 0);`. Does this solve your problem?

BTW. `NavigateTo()` change center and resolution at one time.

**Comment by ndevoecht** [comment]
Hey @charlenni, thanks, I've simplified my code!

I found my issue: MyLocationLayer.UpdateMyLocation has a parameter animated which is true by default. Passing it as false fix my issue.

Thanks for your help!

**Comment by janusw** [comment]
> I found my issue: MyLocationLayer.UpdateMyLocation has a parameter animated which is true by default. Passing it as false fix my issue.

Actually I once had the same problem (and found the same fix).

It seems like `animated=true` is a bad default, since apparently it does not work well in all situations. Maybe it would be worth to change it, and use the more robust unanimated update by default, instead of the more fancy but partly-problematic animation. Anyone who really wants the animation should specify that explicitly.

**Comment by janusw** [comment]
> Mapsui: v2.0.3 (same issue in v3.0.0-alpha.1 - I can't update to v3.0.x because it requires Xamarin.Forms 5) 

Btw, what prevents you from updating to Xamarin.Forms 5? I strongly encourage you to switch to Mapsui v3, which fixes lots of bugs and adds useful features. There will probably be no more bugfixes to v2.
