### ISSUE TITLE
Design proposal for better layer ordering

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1491]
Below is a proposal originating from another thread. Other options can be discussed, but note, there are a lot of things to take into account.

---------------

```c#
    public interface ILayerCollection
    {
        void Clear(); // Removes all layers for all groups
        void Clear(int group); // Removes all layers in a group. No default here. If there is no group argument all layers will be cleared, see Clear()
        void AddToTop(ILayer layer, int group = 0);
        void AddToBottom(ILayer layer, int group = 0);
        void MoveToTop(ILayer layerToMove, int group = 0);
        void MoveToBottom(ILayer layerToMove, int group = 0);		
        void MoveUp(ILayer layerToMove, keepWithinGroup = false); // if it is the top layer in the group it will become the bottom layer in the group above, but not if keepWithinGroup is true
        void MoveDown(ILayer layerToMove, keepWithinGroup = false); // if it is the bottom layer in the group it will become the top layer in the group above, but not if keepWithinGroup is true
        void InsertAbove(ILayer referenceLayer, ILayer layerToInsert);
        void InsertBelow(ILayer referenceLayer, ILayer layerToInsert);
        ILayer Remove(ILayer layer); // Returns the removed layers so that it can be used for moving
    }
```

_Originally posted by @pauldendulk in https://github.com/Mapsui/Mapsui/issues/598#issuecomment-471181466_

**Comment by pauldendulk** [comment]
Random thoughts:
- When referring to a layer to be moved we could use the layer pointer, the layer name, the id within the layer list, some global id. 
- Perhaps we should discuss the internal structure first.
- Another thing to keep in mind is how to persist this information.

**Comment by janusw** [comment]
So, there is already a `Mapsui.Layers.LayerCollection` which has very similar methods, right?

```c#
public class LayerCollection : IEnumerable<ILayer>
{
    public void Clear();
    public void Add(params ILayer[] layers);
    public void Move(int index, ILayer layer);
    public void Insert(int index, params ILayer[] layers);
    public bool Remove(params ILayer[] layers);
}
```

The interface is somewhat different from what you propose, but the functionality is basically the same, right?

So, what exactly do you suggest? Replace this one by the new one? Expand it to include some convenience methods? Or just use it more consequently?

**Comment by charlenni** [comment]
I think, that @pauldendulk proposal is an enhancement of the existing one. With this, you could create groups of layers. E.g. you have on a map the background, the map (tiles) itself and additional layers above the map. If you want layers to stay on top all others, then you have to group them and say, where a new layer should go. You could do this automagical or by hand. Up to now, it isn't possible to move Layers, because it is only a list. They appear in the order, someone added them. If you then add a map later, it is the topmost layer, which hides all others. To bring a special Layer to the top, you have to remove them and readd them again. Each time you do such things, the screen is redrawn. With 5 Layers, you have 6 times to redraw the screen (one clear list and five adds). So the functions to move around layers would be helpful.

**Comment by janusw** [comment]
> I think, that @pauldendulk proposal is an enhancement of the existing one. With this, you could create groups of layers. 

Ah yeah, thanks for the comment. I see the `group` arguments now (obviously I wasn't looking very closely at the code sample). Makes total sense! 😃

**Comment by pauldendulk** [comment]
The main idea is to add grouping. The layers that are part of the Mapview could be in a group that is on top of the main group that the app developer is using.

**Comment by pauldendulk** [comment]
This is implemented in [this PR](https://github.com/Mapsui/Mapsui/pull/2762). Further modifications should be discussed in a new issue.
