### ISSUE TITLE
Fix Bitmap Atlas

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1554]
Updating to the lastest skiasharp broke bitmap atlas in this PR:

https://github.com/Mapsui/Mapsui/pull/1553/files

It can be seen in the images:
-Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/Original/bitmap_atlas.png
-Tests/Mapsui.Rendering.Skia.Tests/Resources/Images/Regression/AtlasSample.Regression.png

The update was necessary to get the project to build at all because of the release of the new MAUI update.

**Comment by inforithmics** [comment]
I'm analysing the situation and it is very strange, I made a git bisect and the Skia.Sharp update introduced this behavior. What is really strange in Skia.Sharp there where no changes in the Code except in the Maui Components. What was changed is that Skia.Sharp is now build on different virtual machines and with different components. So it seems to me the building on new infrastructure caused problems.

What I discovered so far is that Graphics with more then a certain offset are not drawn, so it seems a kind of implicit clipping behavior. I think I'll try to make a minimal skia.Sharp repro. or mapsui repro to see what the problem is.

As a workaround, I'll could make a pull request where only the Maui part relies on the new Skia.Sharp Version and the other parts use the older preview Skia.Sharp version until the real reason is known.

**Comment by inforithmics** [comment]
The reason the Bitmap Atlas does not work is that Skia Sharp does not Render the Full png File. It does not display certain parts.
Will make a reproducible Sample on Skia Sharp for it.

**Comment by inforithmics** [comment]
Here is the link with SkiaSharp issue

https://github.com/mono/SkiaSharp/issues/1981

**Comment by pauldendulk** [comment]
Great work, I now how time consuming this kind of thing can be.

**Comment by pauldendulk** [comment]
This was fixed
