### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by golosalex** [Mapsui/Mapsui#1590]
How to add custom Pin image?

I code something like that:

 
![Screenshot_2](https://user-images.githubusercontent.com/44146357/164204275-f95a6b57-5093-482b-b640-f2282dc12cc1.png)

can you help me?

**Comment by Malstraem** [comment]
Your resource should be embedded

Put in project file
`<EmbeddedResource Include="somedirectory\pic.svg" />`

**Comment by inforithmics** [comment]
I think in your case it sould be `var pinId = this.GetType().LoadSvgId("Resources.Images.Pin.svg");` Because you have to take a type where the Resources is located. typeof(Map) looks in the Mapsui Assembly for the Resource which won't work.

**Comment by golosalex** [comment]
> var pinId = this.GetType().LoadSvgId("Resources.Images.Pin.svg"); its work! ty bro! i sh

**Comment by golosalex** [comment]
can i somehow use my custom user control instead of pin? i want generate custom visual for it and make some interactive? than place my custom control in right place on the map.

**Comment by pauldendulk** [comment]
> can i somehow use my custom user control instead of pin? i want generate custom visual for it and make some interactive, than place my custom control in right place on the map.

Could you please post this as a new question? The idea is that your questions could also help others with similar questions. Also the title could be improved, and please use the template to add the context information (although not all parts of the template have to be used, some things are not relevant). In this case these questions could better be asked in the 'Discussion' tab since they are not real issues in the software.
