### ISSUE TITLE
[WPF&Mapsui 4] BitmapRegistry.Instance._register keeps incrementing

### ISSUE THREAD

**Issue by EjiHuang** [Mapsui/Mapsui#1765]
**Describe the bug**
Hello, I am fetching location information data every second in real time from the server. Then add features to the map. Then add features to the map based on the location information. But when I use CalloutStyle, the _register number of BitmapRegistry.Instance keeps incrementing. I can't find a way how to clear the cached data from BitmapRegistry.Instance._register. Does this have an impact on performance? Sorry, my English is not good.

[wpf, .net core 6, mapsui.4.0.0-beta.5]

**To Reproduce**
This is my test code.
```c#
public void UpdateData(List<LocationPacket> packets)
{
    if (packets is not null)
    {
        _layer.DataSource = new MemoryProvider(CreateFeatures(packets));
    }
}

private List<IFeature> CreateFeatures(IEnumerable<LocationPacket> packets)
{
    var features = new List<IFeature>();
    foreach (var packet in packets)
    {
        var latitude = packet.latitude;
        var longitude = packet.longitude;
        var position = SphericalMercator.FromLonLat(longitude, latitude).ToMPoint();

        features.Add(CreateFeature(packet, position, @"Resources.Embedded.Svg.point.svg", scale: 0.2));
    }

    return features;
}

private IFeature CreateFeature(LocationPacket packet, MPoint position, string embeddedResourcePath, double scale = 0.1)
{
    var feature = new PointFeature(position);

    feature["id"] = packet.id;
    feature["latitude"] = packet.latitude;
    feature["longitude"] = packet.longitude;

    var svgStyle = CreateSvgStyle(embeddedResourcePath, scale);
    feature.Styles.Add(svgStyle);

    var calloutStyle = CreateCalloutStyle();
    feature.Styles.Add(calloutStyle);

    return feature;
}

private IStyle CreateCalloutStyle()
{
    var calloutStyle = new CalloutStyle
    {
        Title = "im a title",
        TitleFont = { FontFamily = null, Size = 14, Italic = false, Bold = true },
        TitleFontColor = Color.White,
        TitleTextAlignment = Mapsui.Widgets.Alignment.Left,
        Padding = new MRect(10f,10f,10f,10f),
        BackgroundColor = Color.Blue,
        Color = Color.White,
        MaxWidth= 240,
        RectRadius = 5,
        ShadowWidth = 0,
        ArrowPosition = 0.5f,
        ArrowHeight = 5,
        ArrowAlignment = ArrowAlignment.Bottom,
        SymbolOffset = new Offset(0, SymbolStyle.DefaultHeight * 1f),
        RotateWithMap = true,
        Type = CalloutType.Single,
        Enabled = true,
    };

    return calloutStyle;
}

```

**Screenshots**
BitmapRegistry.Instance._register
![image](https://user-images.githubusercontent.com/10510947/205592532-15dcf0cc-fd0e-4359-a334-605e9102045b.png)

**Comment by charlenni** [comment]
You create each second all features new, even if they already exist. I would create the MemoryProvider once and cache the features you create. You have the packet ID for this. If you then find the packet ID in the cache, you could use this feature and update the position.

Second, the callout style seems to be fixed, so create it only once. Same for the SVG style.

At the end, I would say, that the increasing _register number is coming from the SVG style. You register each time a new SVG image. So use only one style instance for all your features.

**Comment by EjiHuang** [comment]
@charlenni thank you. Yes, I'm trying to update these features by ID. But, Why use "LabelStyle" does not have this problem. I replace "CalloutStyle" with "LabelStyle", the number of _register does not increase.

**Comment by charlenni** [comment]
The problem is, that for speed reasons, the callout is rendered and then saved as "bitmap". In your case, you create each time a new callout style, that is prerendered ([here](https://github.com/Mapsui/Mapsui/blob/232f41efb42d44de746be0215c6f54bfa85d00d8/Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs#L83)) and saved as a bitmap, even if all of your callouts are looking identical. If you later change anything in the callout, the same ID is reused.

So you have the following choices:
1. You don't use the callout for different data, then you could always use the same style
2. You show only one callout to the user at a time, then you could use the same callout style and change the data before showing the callout
3. You show more than one callout at a time and need different data in the callout, then you create an own style for each feature and have to accept, that you have a special bitmap ID for each of them
4. We look into the code, why the callout style creates a bitmap ID even if the callout isn't visible 😉

**Comment by EjiHuang** [comment]
@charlenni thanks for your help. I see what you mean. I will adjust my code.
