### ISSUE TITLE
Callouts being displayed under LineString

### ISSUE THREAD

**Issue by jamesmontemagno** [Mapsui/Mapsui#1771]
**Describe the bug**
My callouts are getting displayed under the LineString.. not sure how to set the Z cords. In addition I would like to have them displayed where the user tapped... not sure how to adjust that.

![image](https://user-images.githubusercontent.com/1676321/207959619-f0c77cdf-b457-4d92-a3ed-2bf8b6bb5082.png)

**To Reproduce**
My source code for this:

```csharp

                    var g = feature.Geometry as NetTopologySuite.Geometries.MultiLineString;
                    for(var i = 0; i < g.Count(); i++) 
                    {

                        if(i == 0)
                            rgb = ColorConverters.FromHex(feature.Attributes["color"] as string);
                        else
                            rgb = ColorConverters.FromHex(feature.Attributes["color2"] as string);

                        var c = new Mapsui.Styles.Color(rgb.R, rgb.G, rgb.B);

                        var cords = g.Geometries[i];

                       
                        var lineString = new LineString(cords.Coordinates.Select(v => SphericalMercator.FromLonLat(v.X, v.Y).ToCoordinate()).ToArray());
                        var f = new GeometryFeature { Geometry = lineString };

                        var desc = feature.Attributes.GetOptionalValue("desc");
                        var calloutStyle = CreateCalloutStyle(feature.Attributes["name"] as string, desc as string);

                        var v = new VectorStyle
                        {
                            Fill = null,
                            Outline = null,
                            Line = { Color = c, Width = 5 }
                        };

                        f.Styles.Add(calloutStyle);
                        f.Styles.Add(v);

                        features2.Add(f);
                    }
```

Creation of callout:
```csharp
private static CalloutStyle CreateCalloutStyle(string name, string desc = null)
        {
            return new CalloutStyle
            {
                Type = string.IsNullOrWhiteSpace(desc) ? CalloutType.Single : CalloutType.Detail,
                Title = name,
                Subtitle = desc,
                SubtitleFont = { FontFamily = null, Size = 8, Italic = false, Bold = false },
                SubtitleFontColor = Mapsui.Styles.Color.Gray,
                TitleFont = { FontFamily = null, Size = 12, Italic = false, Bold = true },
                TitleFontColor = Mapsui.Styles.Color.Gray,
                MaxWidth = 140,
                RectRadius = 10,
                ShadowWidth = 4,
                Enabled = false,
                SymbolOffset = new Offset(0, SymbolStyle.DefaultHeight * 0.2f),
                Outline = new Pen(Mapsui.Styles.Color.Violet, 2)
            };
        }
```

**Expected behavior**
Should appear on top

**Smartphone (please complete the following information):**
 - Device: Emulators/SImulators 
 - OS: iOS/Android
 - Version ios 16 and latest android

**Additional context**
Nothing that i can think of.

**Comment by charlenni** [comment]
That is, because you add first the CalloutStyle and then the VectorStyle. Mapsui goes through the styles in the order they are added. So the CalloutStyle is drawn and then, above, the VectorStyle. Add it vice versa and it will drawn correct.

**Comment by charlenni** [comment]
One more think. If you want to have the CalloutStyle on top, you should make the callout layer the top most layer.

**Comment by jamesmontemagno** [comment]
I tried that as well @charlenni... I think the problem is maybe that the callout here actually belongs to the purple line... but is being drawn under it... i guess i could try to re-order things so that I add the top layers first so the callouts are near the bottom are always at the top...hmmmm

here for example in my image the callout belongs to a different one

![image](https://user-images.githubusercontent.com/1676321/207985566-039fb566-ace9-4fdc-8ebb-009f8b4f49ae.png)

let me try some different ordering

**Comment by charlenni** [comment]
Ok, for that you should have a look, how the features are drawn in the draw process. You could find this [here](https://github.com/Mapsui/Mapsui/blob/b17b63db4a75b56c83602a915f235584b8c0934b/Mapsui/Rendering/VisibleFeatureIterator.cs#L25). 

There is an outer loop over all layers. Inside of this, the first loop iterates through all styles the layer contains. For each of these styles, all features are drawn (if the conditions fulfilled). The second loop goes over all features and draws all the styles, that belong to this feature.

In your case, you added the styles (vector and callout) to the feature itself. With this, the first loop draws nothing (no style for the layer). The second loop draws feature 1 as vector and then as callout. After that, the second feature is drawn as vector (perhaps over callout from feature 1) and then as callout. As you see, you don't get, what you want.

So, if you want the callouts over all other features, you need a second layer: one layer for your line strings and one layer for the callouts (point features with callout style). Use a dictionary to connect your line string features with your point features, so that you could show and hide the callouts.

**Comment by jamesmontemagno** [comment]
Thanks for the help and clarification on this! Super helpful.
