### ISSUE TITLE
[Uno] Rendering not working on Android and unable to build for iOS

### ISSUE THREAD

**Issue by nickrandolph** [Mapsui/Mapsui#1812]
**Describe the bug**
Two issues, both can be seen in the code on the PR into the Uno.Samples repository (https://github.com/unoplatform/Uno.Samples/pull/279):
- Android builds and runs but doesn't display map
- iOS doesn't build with a skia related warning

The iOS build issue appears to be fixed if the latests packages are used (eg https://github.com/Mapsui/Mapsui/actions/runs/4051847676#artifacts)

**To Reproduce**
1. Retrieve the PR code from Uno.Samples repository and open the MapControlSample sln
2. Attempt to build and deploy for iOS - this will fail to build
3. Build and run on Android - this will fail to show map

**Expected behavior**
iOS and Android should build, run and show map

**Comment by pauldendulk** [comment]
Is this about the Mapsui.Uno or Mapsui.Uno.WinUI package?

**Comment by nickrandolph** [comment]
I'm guessing it applies to both but I was testing with Mapsui.Uno.WinUI

**Comment by inforithmics** [comment]
So I checked out the pull request and it builds.
I used Visual Studio 2022 on Windows to build. 
@nickrandolph  did you use Visual Studio for Mac?

I saw that no global.json is specified in the sample I would add following global.json.

12 lines (12 sloc)  213 Bytes

```
{
  "sdk": {
    "allowPrerelease": false,
    "version": "7.0.100",
    "rollForward": "latestMajor"
  },
  "tools": {
	"allowPrerelease": false,
    "dotnet": "7.0.100",
    "rollForward": "latestMajor"
  }  
}
```

If dependency on .NET 7 Sdk is not desired then i would add latest .NET 6 Sdk

```
{
  "sdk": {
    "allowPrerelease": false,
    "version": "6.0.300",
    "rollForward": "latestMajor"
  },
  "tools": {
	"allowPrerelease": false,
    "dotnet": "6.0.300",
    "rollForward": "latestMajor"
  }  
}
```

The reason I specified .NET 7 sdk dependency is that a lot of bugs where fixed with uno in newer sdk versions.

If you are building on Mac I have to investigate if it works now. But you have to use the newest Visual Studio for Mac maybe even Visual Studio for Mac Preview. I'll test it.

**Comment by inforithmics** [comment]
I tested the Pull Request with Visual Studio 2022 for Mac (Preview) will come out around next week and the Android did display the Map. But the iOS didn't properly compile I guess I should add a target for ios in Mapsui.Uno.WinUI as for android.

**Comment by inforithmics** [comment]
Pull request where I try to build it on Mac (Github action).

https://github.com/Mapsui/Mapsui/pull/1815

**Comment by nickrandolph** [comment]
>>"I saw that no global.json is specified in the sample I would add following global.json."
We typical don't specify global.json unless we need to pin the sdk. I'm running latest net7sdk updates with VS2022 (on windows) so there shouldn't be any issues for building ios/android targets. 

As I mentioned, it's the nuget package that's failing to build for iOS. I grabbed the latest packages from the CI pipeline and that works for ios

For Android I was testing on the simulator running an older Android version. Also, I've tried the samples in the mapsui repo and they work on Android, so I'm not sure what's different about the uno sample. Did you run the PR from uno.samples on VS2022 for win on android?

**Comment by inforithmics** [comment]
The reason I suggested to pin it at least at version 6.0.402 was that after this checking which pinned it at least at this version.
https://github.com/Mapsui/Mapsui/commit/15fce4a931d3372cd26635307f2a0346c71dd0d8

Mapsui worked better on Uno (meaning it run through on the Builld Service. Because There were some significant Bugfixes that allowed to make Mapsui.Uno and Mapsui.Uno.WinUI to work.

I tried compiling it on Windows Visual Studio 2022 Preview (which worked). This should be relased next week or so. I couldn't run the Android Emulator because I'm running Windows on ARM with an Visual Studio for Arm Edition were the Simulator is not avaible yet.  But I run it on Visual Studio on Mac 2022 Preview on a Mac were the Android Simulator worked. (With a Preview 7.0 Sdk (which too should be released next week). So when the Visual Studio 2022 17.5 officially gets released I'll test it  if everything works.

**Comment by inforithmics** [comment]
@nickrandolph  There is a new Mapsui Version 
https://www.nuget.org/packages/Mapsui.Uno/4.0.0-beta.7
https://www.nuget.org/packages/Mapsui.Uno.WinUI/4.0.0-beta.7

Have you tried it?

**Comment by nickrandolph** [comment]
Not yet, will try it over next couple of days and report status

**Comment by inforithmics** [comment]
Following Properties are set in the working Android WinUI Project (this things are not set in the Uno.Sample) so I think setting them could help. 

```
<SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-android'">21.0</SupportedOSPlatformVersion>
	<!-- Workaround for https://github.com/unoplatform/uno/issues/9723 -->
	<_AndroidApiLevel Condition="'$(TargetFramework)' == 'net6.0-android'">31</_AndroidApiLevel>
```

**Comment by nickrandolph** [comment]
I've tested latest package (beta4) both iOS and Android with a bit of mixed results:
**Android**
Builds correctly and runs without error. Map displays fine on a real device (Pixel Pro 7) and on emulator running API level 33. Doesn't render on API level 30. Is there something that would prevent it working on devices running old API level?

**iOS**
Updated to latest package and was initially getting build errors when attempting to deploy. Cleaned bin/obj folder and rebuilt and it's working now, so probably just a temporary issue with cached dependencies.

Happy to close this issue now but would be interested to know more about the constraints on API level and whether this can be enforced (or warned) by tooling
