### ISSUE TITLE
[Uno] MapsUI 4 beta9 viewport doesn't respect center

### ISSUE THREAD

**Issue by FrozDark** [Mapsui/Mapsui#1949]
**Mapsui Version**
MapsUI.Uno.WinUI 4.0.0 beta9

**Mapsui Platform**
Uno

**Device**
Android

**Describe the bug**
The viewport center has offset by the size of rectangle

**To Reproduce**
[MapsUIUnoIssues.zip](https://github.com/Mapsui/Mapsui/files/11181157/MapsUIUnoIssues.zip)
1. Download repro
2. Run Android
3. Click on mid button "Center on point" and the point will not be at center

**Expected behavior**
Respect viewport center

**Screenshots**
![agaga2](https://user-images.githubusercontent.com/6670150/230669308-35bf2caa-22f1-45ee-aedc-a8f8fd3f9562.jpg)

**Additional**
It's been present in beta 8

**Comment by pauldendulk** [comment]
> It's been present in beta 8

The bug was present in beta 8? Or the correct functionality was present in beta 8?

**Comment by pauldendulk** [comment]
I tested on Windows and there it works correctly. Did not get around testing it on Android this morning.

Since I see the offset in both x and y direction is incorrect it could be related to PixelDensity. Since the image also looks a bit blurred it could be that the image is not drawn with the correction for the higher pixel density. So, it is drawing outside the canvas. 

Could you test with the Mapsui source running it on Android and using the 'Navigation' | 'Center on Location' sample. London Ontario should be in the center of the map.

**Comment by FrozDark** [comment]
> > It's been present in beta 8
> 
> The bug was present in beta 8? Or the correct functionality was present in beta 8?

yep. It was present in beta8. I just thought it might be related to https://github.com/Mapsui/Mapsui/issues/1842
But fixing it doesn't resolve the issue. So I opened up this one.


> I tested on Windows and there it works correctly. Did not get around testing it on Android this morning.
> 
> Since I see the offset in both x and y direction is incorrect it could be related to PixelDensity. Since the image also looks a bit blurred it could be that the image is not drawn with the correction for the higher pixel density. So, it is drawing outside the canvas.
> 
> Could you test with the Mapsui source running it on Android and using the 'Navigation' | 'Center on Location' sample. London Ontario should be in the center of the map.

I'll check up and give you feedback

**Comment by FrozDark** [comment]
> I tested on Windows and there it works correctly. Did not get around testing it on Android this morning.
> 
> Since I see the offset in both x and y direction is incorrect it could be related to PixelDensity. Since the image also looks a bit blurred it could be that the image is not drawn with the correction for the higher pixel density. So, it is drawing outside the canvas.
> 
> Could you test with the Mapsui source running it on Android and using the 'Navigation' | 'Center on Location' sample. London Ontario should be in the center of the map.

I've run sample on Android and it's centered on London as expected
![photo_2023-04-10_13-05-00](https://user-images.githubusercontent.com/6670150/230846741-2d8809f1-60ad-4bf6-8a96-7a5fcc2bd373.jpg)

**Comment by FrozDark** [comment]
Uno like oversized
![230669308-35bf2caa-22f1-45ee-aedc-a8f8fd3f9562](https://user-images.githubusercontent.com/6670150/230848501-bb3c5d31-e8ab-4044-8db6-83b5fe32f9e5.jpg)

**Comment by FrozDark** [comment]
> I would like to reproduce the problem but when I try to build UnoIssues.Mobile I get this compile error:
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1705	Assembly 'Mapsui.UI.Uno.WinUI' with identity 'Mapsui.UI.Uno.WinUI, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=16.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=16.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'	UnoIssues (net7.0-windows10.0.19041.0)	C:\Users\pauld\Downloads\MapsUIUnoIssues\UnoIssues\UnoIssues\CSC	1	Active
> ```

It's cause of mapsui is built upon higher version of Microsoft.iOS while uno.check is installing the old one for some reason.  Previously

**Comment by inforithmics** [comment]
I tested the sample on follwing Android platforms.
Android Emulator on MacOS: works
Android Emulator on Windows: does not work:
Android Subsytem on Windows: works:

So I could reproduce the problem. Some General things I discovered. Mapsui targets Uno.UI 4.6 But the sample targets uno.ui which targets uno.ui 4.8 which uses the new uno template which was introduced in uno.ui 4.7. Maybe mapsui.uno needs to target 4.7 and update the uno.ui samples.

**Comment by pauldendulk** [comment]
I just ran the sample on the Windows Android emulator and I could not reproduce the problem there. So, that differs from Thomas' result. Could it depend on the device? I ran it with a pixel 5 api 30 5554. Or could it be a problem with the emulator?

**Comment by FrozDark** [comment]
> I just ran the sample on the Windows Android emulator and I could not reproduce the problem there. So, that differs from Thomas' result. Could it depend on the device? I ran it with a pixel 5 api 30 5554. Or could it be a problem with the emulator?

Sample or repro?

Could you try on Pixel 5 api 33 with 1080x2340 resoulution and 440 density? 
I've tested on emulator and real devices and issue was present everywhere

**Comment by pauldendulk** [comment]
> Sample or repro?

The repro, UnoIssues, but earlier also with Mapsui.
 
> Could you try on Pixel 5 api 33 with 1080x2340 resoulution and 440 density? I've tested on emulator and real devices and issue was present everywhere

Yes! Now I can reproduce it. So, it depends on the device. I can also reproduce it with the 'Center on locations' sample in Mapsui.

**Comment by pauldendulk** [comment]
I don't understand the situation yet. 

I think the Navigator.CenterOn is irrelevant. It works correctly. It is just a problem with the scaling.

In GetPixelDensity I replaced `return (float)(XamlRoot?.RasterizationScale ?? 1f);` with `return (float)DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel` but the behavior remains the same. They both return 2.8125.

If I hard code 2 instead of 2.8125 it does seem to center correct. So it could be a rounding error, but in that case it looks like this is not in our code.
![image](https://user-images.githubusercontent.com/963462/231091501-ccdf4d29-af8a-4deb-8857-2dfb7abed07c.png)

If it is a rounding issue then perhaps the pixel with api 30 that failed to reproduce it has integer values. I checked and it does not. It's RawPixelsPerViewPixel is 2.75. No reason it should be rounded in a different way.

I am actually surprised there is a difference at all since it is the exact same device, only the Android version is different.
![image](https://user-images.githubusercontent.com/963462/231094596-385624c5-f797-45cc-9528-56f45e9bf2ba.png)

So, what could be the difference? Perhaps we should not use RawPixelsPerViewPixel. So, I looked at the difference in the `DisplayInformation.GetForCurrentView().`. 

Api 33:
![image](https://user-images.githubusercontent.com/963462/231097458-ee6e55b9-c8b1-44de-a01b-3021233c2438.png)

Api 30:
![image](https://user-images.githubusercontent.com/963462/231097688-39ee43eb-beb8-4550-a4d4-e4624e8ce41f.png)

ResolutionScale is an enum in API 33 instead of double in API 30. I guess that is what should be used.

**Comment by pauldendulk** [comment]
I can get the app to display correctly on both devices with the code below. 

```csharp
private float GetPixelDensity()
{
#if __WINUI__
    return (float)(DisplayInformation.GetForCurrentView().ResolutionScale / 100.0);
#else
    return (float)DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;
#endif
}
```

I will create a PR for this. It does not make much sense to me. And I did not run into any documentation on this.

**Comment by pauldendulk** [comment]
Something else, the issue with the Microsoft.iOS version mentioned above is also something we may need to deal with. @inforithmics Do you have any ideas about this?

**Comment by pauldendulk** [comment]
What is weird about the solution (or perhaps it should be called a workaround) it that it means a Uno app will show a map with less quality when it is running on API 33 instead of 30 on the same device.

Further a regular Xamarin.Android app running on API 33 will also have a higher resolution than a Uno app on exactly the same device with the same OS. 

And Xamarin.Android returns 2.75 and not 2.8125 as pixel density.

**Comment by FrozDark** [comment]
@pauldendulk do we need to ask Uno maintainers about the issue with resolution?

**Comment by pauldendulk** [comment]
> @pauldendulk do we need to ask Uno maintainers about the issue with resolution?

I was about to post an issue. Or do you suggest another way to contact them?

**Comment by inforithmics** [comment]
It has to do something with the dpi, because I created a Device with 1024 * 600 and m-dpi and there it worked even with Android 13.0 (API 33)

**Comment by inforithmics** [comment]
The funny thing is because I have two monitors with different resolutions,  moving the simulator from the lower to the higher resolution, centers correctly for a short time until it redraws.

**Comment by inforithmics** [comment]
<img width="197" alt="image" src="https://user-images.githubusercontent.com/2290863/231114838-60e5d098-3a67-4e2e-a45a-290cefd52530.png">

**Comment by pauldendulk** [comment]
@inforithmics interesting 🤔

@FrozDark you did also see the issue on a real device, right?

https://github.com/unoplatform/uno/discussions/11943

**Comment by pauldendulk** [comment]
> I've tested on Poco F3 and Samsung A72. Both on android 13. Both have the issue but scale differs

Good, it would be silly if it is just an emulator issue.

**Comment by inforithmics** [comment]
I think I know now what happens. The Pixel Density is retreived from following Code 

`return (float)(XamlRoot?.RasterizationScale ?? 1f);`

This meeans when the XmlRoot isn't set yet it returns 1 what happens.

Internally this is mapped in Uno to
` return (float)DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;`

**Comment by pauldendulk** [comment]
That looks suspicious and I looked at that too but this is not what happens. PixelDensity is not 1 initially. That also does not explain with a scale of 2.0 fixes the problem. I think [this](https://github.com/Mapsui/Mapsui/issues/1949#issuecomment-1502883938) post gives some insight in what is happening. I think it makes no sense that a scale of 2.0 fixes the problem. The device has a DPI and that DPI is 2.75. Using that scale should produce the correct result. It looks like there is some other scaling going on that interferes with it.

**Comment by inforithmics** [comment]
@pauldendulk 

You are right.

```
 #if HAS_UNO
         return (float)DisplayInformation.GetForCurrentView().ResolutionScale / 100.0f;
 #elif __WINUI__
         return (float)(XamlRoot?.RasterizationScale ?? 1f);
#else
        return (float)DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;
#endif
```

should fix the issue because Real winui needs return (float)(XamlRoot?.RasterizationScale ?? 1f); or else it crashes on startup. (I added it to my pull request review).

This seems to be broken on Uno platform. So the uno issue is correct.
return (float)DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;

**Comment by pauldendulk** [comment]
@FrozDark beta.10 was released.

**Comment by pauldendulk** [comment]
It was confirmed that this was a bug in Uno which is fixed in their new dev release. The fix does not break the workaround we had but still we should revert back to using `(float)(XamlRoot?.RasterizationScale ?? 1f);` when they have a non-dev release. https://github.com/unoplatform/uno/issues/11944#issuecomment-1510920034
