### ISSUE TITLE
Support Avalonia 11

### ISSUE THREAD

**Issue by slater1** [Mapsui/Mapsui#1992]
**Mapsui Version**
4.0.0-beta.11

**Mapsui Platform**
Avalonia

**Device**
Windows

**Describe the bug**
Requires ReactiveUI >=0.10.19 && < 1.0.0

**To Reproduce**
1. Create new avalonia project from template
2. Add Mapsui.Avalonia nuget reference
3. Observe NU1608 `Detected package version outside of dependency constraint: Mapsui.Avalonia 4.0.0-beta.11 requires Avalonia.ReactiveUI (>= 0.10.19 && < 1.0.0) but version Avalonia.ReactiveUI 11.0.0-preview6 was resolved.`	

  ![image](https://github.com/Mapsui/Mapsui/assets/2089725/7bffe41f-244b-43fc-8538-59c38a54a375)

**Expected behavior**
I can use Mapsui.Avalonia in Avalonia 11.

**Comment by slater1** [comment]
I see you're already working on this. Is there anything I can do to help?

https://github.com/Mapsui/Mapsui/compare/master...feature/upgrade-avalonia

**Comment by slater1** [comment]
This is pretty much a duplicate of https://github.com/Mapsui/Mapsui/issues/1823

Closing.

**Comment by pauldendulk** [comment]
> I see you're already working on this. Is there anything I can do to help?
> 
> #1829

@slater1 The problem is how to decide between V11 which is still in preview and v0.10 which will be used for a while. I was secretly hoping that V11 would be released in the meantime, but it is not and we will release the Mapsui release candidate the coming weeks. 

One option would be to add a separate package for preview 11. For Uno we have something similar with the Mapsui.Uno and Mapsui.Uno.WinUI packages side by side. Perhaps we could add a Mapsui.Avalonia.V11 package. That is not very future proof however (what do when V12 comes out?). Renaming our existing package to Mapsui.AvaloniaV0 might be a better option. @inforithmics What do you think?

**Comment by pauldendulk** [comment]
> Yes I think, there should be a Avalonia Preview nuget. I'm not sure yet if it should be called Mapsui.Avalonia.V11. Maybe Mapsui.Avalonia.Preview or something similar.

That sounds like the best solution for as long as it is actually in preview, but what if V11 is released? If at that point we change Mapsui.Avalonia to V11 this will be a breaking change for the V0 uses who would then be forced to upgrade, even though the Mapsui version itself has no major change.

**Comment by inforithmics** [comment]
Then I think renaming Avalonia to avaloniav0 would be the better solution. Because I hope or guess that avalonia v12 would have less breaking changes. If there are we could introduce avaloniav11 package than. So the numbered Avalonia packages are „stable“ and Avalonia without number is always upto date
