### ISSUE TITLE
MapView: Drawable with IsClickable=false blocks MapClicked event

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#2041]
**Mapsui Version**
4.0.0-rc.2

**Mapsui Platform**
Xamarin.Forms

**Device**
iOS 16 (probably also Android and others)

**Describe the bug**
I have a `MapView` with several `Drawables`. The `IsClickable` property is true for some and false for others. The clickable Drawables receive `Clicked` events as expected. The unclickable ones do no receive such events (also expected), but they seem to block the `MapClicked` event, which is actually not what I expected.

**Expected behavior**
If the Drawable at the clicked position is not clickable, i.e. does not handle the click event, I'd expect that the event is handed down to the map itself and the MapView emits that MapClicked event, as if there was no drawable at the position.

If there is another (clickable) Drawable at the same position, it should be able to handle the click event (which also does not seem to work).

**Comment by pauldendulk** [comment]
That is also what I would expect. @charlenni Do you also consider this a bug?

**Comment by janusw** [comment]
I think I found the place in the code which breaks this (am about to submit a PR) ...

**Comment by janusw** [comment]
> The unclickable ones do no receive such events (also expected), but they seem to block the `MapClicked` event, which is actually not what I expected.

This is fixed by #2043 (with little effort).

 
> If there is another (clickable) Drawable at the same position, it should be able to handle the click event (which also does not seem to work).

I verified once more that this problem indeed exists as well. It is not fixed by #2043 (will probably require some more effort).

**Comment by pauldendulk** [comment]
> `IFeature.IsClickable`

If possible I would like to avoid adding this to the interface. A lot of scenarios can be solved by using custom IFeature types which could be cast back to that type in user code. So you could add `ClickablePointFeature: PointFeature`. with a IsClickable field, and in the MapInfo event cast back to that type to check the IsClickable.

btw, there is a MapInfo.MapInfoRecords field with a list of all the clicked items. The MapInfo.Feature is the top one, but in fact the MapInfo.Feature could be removed entirely if it causes confusion.

**Comment by janusw** [comment]
> > `IFeature.IsClickable`
> 
> If possible I would like to avoid adding this to the interface. A lot of scenarios can be solved by using custom IFeature types which could be cast back to that type in user code. So you could add `ClickablePointFeature: PointFeature`, with a IsClickable field, and in the MapInfo event cast back to that type to check the IsClickable.

Hm, so maybe not in `IFeature` itself, but one of its descendants? `GeometryFeature` might be a good candidate, since `Drawable` is based on this. Would it be ok to have an `IsClickable` property in the `GeometryFeature` itself, or would you prefer a subclass `ClickableGeometryFeature`?
In general, I would avoid making the `IFeature` inheritance tree too complicated. Probably most (all?) features could be clickable in principle. I guess the `IsClickable` property will need to be handled in `Mapsui.Rendering.Skia.MapRenderer.GetMapInfo` or similar.

**Comment by pauldendulk** [comment]
I need to dig into this further to come up with a better proposal. I want to push hard for the simplest solution. I did not do this enough in the past and promised myself to do it more in new code. If we could avoid an IClickable field altogether this would be the best option.

- First thing is to make sure your scenario is possible at all.
- Second thing is to make your scenario easier. But still, my approach would be not to add specific solutions to specific scenarios, but to provide the building blocks to compose the desired functionalty.

About the first point. What if you use the Info event instead of MapClicked and check a field in the IFeature. You could set a property like this `myFeature["isClickable"] = true` and check for `if (clickedFeature["isClickable"] == true)`? (you might need a cast). 

A related thing I am thinking about is to make it possible to add any kind of class to a feature  without having to use inheritance (because you are definitely right the inheritance tree should not be too complicated). Perhaps IFeature should have a Data field of type T.

**Comment by pauldendulk** [comment]
I would think clickable/non-clickable could be solved by putting those two in different layers. The MapView has it's own layers which is why this work different there, but at some point the same kind of layers will need to be used.

**Comment by pauldendulk** [comment]
@janusw Was this now fixed with your workaround?

**Comment by janusw** [comment]
Yes, I think this issue is fully fixed by now (with v4.0.0), the first part via #2043, the second via #2060.
