### ISSUE TITLE
Mapsui.Maui - System.Reflection.TargetInvocationException (Mac Catalyst)

### ISSUE THREAD

**Issue by Visutronik** [Mapsui/Mapsui#2068]
**Mapsui Version**
Mapsui.Maui 4.0.0-rc.3

**Mapsui Platform**
Maui - Project only for MacCatalyst

**Device**
MacOS

**Describe the bug**
I get the Exception "System.Reflection.TargetInvocationException" in the Program.cs when I try to create a MapControl in my page.

**To Reproduce**
1. Create a new Maui project on a Mac
2. Add the libraries for Mapsui
3. Steps on the "Getting started" page of Mapsui (https://mapsui.com/documentation/getting-started-maui.html)
4. Run the program

**Additional context**
I removed Android & iOS in the project file

**Comment by pauldendulk** [comment]
Thanks for the bug report. 
- Did you add the `true` in `.UseSkiaSharp(true)`?
- Did you run a `dotnet workload install maui-maccatalyst`?

**Comment by Visutronik** [comment]
Thanks for the fast answer.
Yes, i added the true
No. I run the command now and restartet Visual Studio 2022. But the problem still exist.

**Comment by pauldendulk** [comment]
Thanks.
Deleted the bin and obj?

**Comment by Visutronik** [comment]
I delete the bin and obj but it doesn't solve the problem.

**Comment by pauldendulk** [comment]
Thanks for the testing. Some more to try:
- `workload install maui` 
- Upgrade to the latest visual studio for Mac (or are you using VS code?).
- Install the latest .NET 7 SDK.
- Delete the project and create it again with the new tools.

@inforithmics Could you test if the getting started works on your machine? If so, it would not block the release. I would expect this something quite a lot because maui is our most used package and any maui develop on Mac would try this as one of the first things. I guess we need to start to add requirements to our getting started. It is hard to maintain though. Perhaps just advise to use the latest of everything.

**Comment by inforithmics** [comment]
My guess is that GPU is not supported on MacCatalyst
MapControl.UseGPU= false;

**Comment by inforithmics** [comment]
I tested it and setting MapControl.UseGPU = false, mapsui works on maccatalyst.
Made a pull Request to set the correct default on MacCatalyst

**Comment by pauldendulk** [comment]
Great you found the problem. Is also means it never worked for anyone on Mac. If I were a Mac developer it would be one of the first things to try.

**Comment by pauldendulk** [comment]
This should be fixed with #2070 which will be part of the release.

**Comment by Visutronik** [comment]
I'm sorry to say this but i get still the exception...
I used the last version of Visual Studio (installed it last week).
Are there a minimum MacOS system? I use MacOS 13.2.1

I should say, this is my first that i try to create a project on a Mac. Normally i worked on Windows.
