### ISSUE TITLE
[Uno.WinUI] Mapsui.Uno.WinUI restricts Uno.WinUI to <5.0.0

### ISSUE THREAD

**Issue by kazo0** [Mapsui/Mapsui#2238]
New Uno.WinUI dev packages are now at 5.1.0 with the upcoming release of Uno 5.0.x

**Mapsui Version**
Mapsui.Uno.WinUI 4.1.1

**Mapsui Platform**
Uno.WinUI (5.1.0-dev.130)

**Describe the bug**

`Mapsui.Uno.WinUI 4.1.1 requires Uno.WinUI (>= 4.9.20 && < 5.0.0) but version Uno.WinUI 5.1.0-dev.130 was resolved`

**To Reproduce**
1. Install Mapsui.Uno.WinUI 4.1.1 with an Uno app using [latest Uno.WinUI dev packages](https://www.nuget.org/packages/Uno.WinUI/5.1.0-dev.137)
2. Build
4. See error/warning

**Comment by inforithmics** [comment]
The artifacts of this pull request https://github.com/Mapsui/Mapsui/pull/2179 use uno.winui 5.0 Waiting for Release Version of Uno.WinUI

**Comment by pictos** [comment]
@inforithmics the PR is merged, so this issue can be closed or still there's something else to address?

**Comment by kazo0** [comment]
The current packages, including 4.1.2-preview.1, still restricts to <5.0.0 so I think this should stay open until a new package is available

**Comment by pauldendulk** [comment]
ah, that is a small thing I can fix as well.

**Comment by pauldendulk** [comment]
@kazo0 I create a PR to set the upper limit to 6.0.0 like: 4.9.20,6.0.0
https://github.com/Mapsui/Mapsui/pull/2318/files

There are some choice I had to make that I am not sure about, I like to hear your opinion @kazo0.
- With this range we support version across two major version (4 and 5). Since there were probably breaking changes when going to 5 our library should in theory support different versions of Uno.WinUI. But with the limit as above the build will resolve to 4.9.20 and that is what our software is tested on. So, there we should not be surprised if it does not work with v5.
- Usually when we upgrade the lowest limit is set to the highest version at that moment in time, because that is what we test with. In this case we release a patch, so the users should expect hardly any change. So, increasing the lower limit would be an unpleasant surprise.

A more general problem we have just one release for all different platforms. Those platforms upgrade in their own cadence. Eventually we may need to go for separate releases for each platform.

**Comment by jeromelaban** [comment]
@pauldendulk we introduced binary breaking changes in Uno 5, which make some packages incompatible between versions. 

For the lowe bound specification, if mapsui builds with Uno 5.0.19 (the lowest available 5.x build), the version for your package may be `[5.0.19, 6.0.0)`.

On the upper bound specification, we guarantee that all 5.x builds are binary compatible, and it may also be true that the Uno API surface that Mapsui uses will be compatible with future Uno 6.x builds (we do not know yet). For instance, SkiaSharp is compatible with both Uno 4 and 5, because it is not using any of the breaking APIs, and it may be the case for mapsui in the future.

I would suggest not putting any upper bound until is its known that a Mapsui build really is not compatible with a future version.

**Comment by jeromelaban** [comment]
@pauldendulk In general, setting `5.0.19` without any range qualifier will do.

**Comment by pauldendulk** [comment]
I assume this was fixed in 4.1.2.
