### ISSUE TITLE
Breaking changes in changeset Feb 11, 2024, 08:88 e41e3536fd58417dc84099c13038bf0bc8bbc69b ?

### ISSUE THREAD

**Issue by starnutoditopo** [Mapsui/Mapsui#2498]
**Mapsui Version**
Changeset Feb 11, 2024, 08:88 e41e3536fd58417dc84099c13038bf0bc8bbc69b

**Mapsui Platform**
Wpf

**Device**
Windows

**Describe the bug**
In a WPF application, I implemented a widget with dragging features capabilities (according to the existing example, as in https://stackoverflow.com/a/77807240/1288109 ).
User can insert a new feature (a marker) and drag it around a map.
My application works fine with rev 8c776588f2c86565d98ddce2d3b7b8f464ebc30b of Feb, 10, 2024, 17:09.
Switching to the subsequent revision on Main, no error is reported at build time, and my application still starts.
At run-time, though, when the user performs a dragging operation, the marker is moved together with the underlying maps, so the effect is not to move the marker over the map, but to pan all layers.

**Comment by pauldendulk** [comment]
In main there are many breaking changes. We are still before the release of 5.0.0-beta.1 and when that is released we are going to tell people that there will be more breaking changes. 

But perhaps you are pointing us to a bug we introduced. For this we need some more information. The editing samples have bugs they way they are now (differences in behavior between platforms) so it is hard to tell what the bug is. There need to be breaking changes in the widgets events to fix this. Still, the end result of v5 should that editing works properly. So, I'd be interested in more information.

**Comment by starnutoditopo** [comment]
I just reported it because I noticed the different behavior, but it
definitely looks like you are aware of it. That's fine.

If you want to have a look, I added you as a collaborator to my pet project
https://github.com/starnutoditopo/WpfFly. I'd like to open-source it, if I
manage to make it work (it contains some unit-tested facilities to
calculate rhumb bearing and rhumb distance: feel free to grab them, if you
think they may be useful for mapsui!).

**Comment by pauldendulk** [comment]
Mapsui 5.0.0-beta.1 was released with a major update of touch and mouse handling. I would be happy with some testing. Here is a checklist with suggestions on how to test: https://mapsui.com/v5/documentation/touch-and-mouse-handling.html. Please create new issues for the things you find.
