### ISSUE TITLE
Minimum space between features to prevent overlapping

### ISSUE THREAD

**Issue by Saliom** [Mapsui/Mapsui#2512]
**The problem**
When having features like circles or pins close to eachother they sometimes overlap and some are hidden when the map is zoomed out.

**The proposed solution**
An option to set the minimum space or gap between the position of features to prevent overlapping without changing their real position on the map when they are not overlapping (ex: when the map is zoomed in).

**Additional context**
Zoomed out
![image](https://github.com/Mapsui/Mapsui/assets/7543712/1075d25e-d9ad-4f9d-b214-b55be1b87ccf)
Zoomed in
![image](https://github.com/Mapsui/Mapsui/assets/7543712/1095602c-309f-40e5-8cdb-e742b824e8a8)

If there's any workaround or way to achieve the wanted result until a proper solution is released please feel free to share.

**Comment by pauldendulk** [comment]
But wat do you expect to happen when two features are too close together? Move them away from each other? Away from their actual position? And what to do if other features are an all sides and it can not move in any direction?

I think the general thing you are looking for is 'clustering'. There are many ways to go about this in general but Mapsui does not have a lot of in-built support for this. The only thing way have is stacked labels. You can see those in the [online samples](https://mapsui.com/samples/) under: Special -> Stacked labels.

![image](https://github.com/Mapsui/Mapsui/assets/963462/601677bd-3d01-44b0-a39b-590b46160b3e)

Other solutions (not in Mapsui) show features close to each other as a single symbol that is bigger and with a number on it (but there are many other solutions for this). 

The StackedLabelProvider returns different features depending on the zoomlevel and it has a simple kind of clustering algorithm used for the rectangle. You could write your own version of the StackedLabelProvider where you could return the features themselves as a single point with a different symbol to indicate it is a group.

**Comment by Saliom** [comment]
Yes the wanted result would be to move the features away from their actual position if they are closer than X pixels than another feature of the same layer for example. And if other features are on all sides it would have to push one or more of them to make enough space until the "gap" between each of them is respected.

I'm not sure 'clustering' could be a solution as it doesn't seem to change their displayed position at any zoom level to keep them in some sort of 'box'.

Now that I think about it, it might be "easier" to just redraw every feature and offset the ones that are too close to each others on each zoom in/zoom out. It could however make the app lag or slow down heavily depending on the number of features to redraw. 

I also think another event alongside "MapControl.Map.Navigator.ViewportChanged" but only for Viewport.Resolution could be great to not have to call tons of methods on each map move when trying to listening only to resolution changes!

**Comment by pauldendulk** [comment]
> Yes the wanted result would be to move the features away from their actual position if they are closer than X pixels than another feature of the same layer for example. And if other features are on all sides it would have to push one or more of them to make enough space until the "gap" between each of them is respected.

The fact to you draw the feature on the wrong position seems odd to me. The fact that the displaced feature influences yet another feature will make it more complicated. The algorithm may need a few iterations (not impossible). If you have something similar to a pin, I would expect the point of the pin to be in the correct place. The top part of the 'pin' could be displaced. Maybe this is more like a balloon, where the string of the balloon is attached to the correct place on the map and the balloon itself can be moved away from other balloons. Actually the balloon with be more like a label than a symbol. 
 
> I'm not sure 'clustering' could be a solution as it doesn't seem to change their displayed position at any zoom level to keep them in some sort of 'box'.

There are many ways to deal with clustering. It is about features being too close together, which is also what you are dealing with, so I think it can help if you search for clustering in map. Professionals have been thinking about solutions for this for decades, so you might learn something.

> Now that I think about it, it might be "easier" to just redraw every feature and offset the ones that are too close to each others on each zoom in/zoom out. It could however make the app lag or slow down heavily depending on the number of features to redraw.
> 
> I also think another event alongside "MapControl.Map.Navigator.ViewportChanged" but only for Viewport.Resolution could be great to not have to call tons of methods on each map move when trying to listening only to resolution changes!

About ViewportChanged. We need to redraw the map on every change of resolution and/or center. When you are mouse wheel zooming both change at the same time. By working with a ViewportChanged instead of separate resolution and center changes we managed to cut the number of map updates in half. That in itself was a big performance improvement. 

If you really need to listen to resolution changes you could compare the current resolution with the OldViewport that is in the event args. 

A better solution is to implement your algorithm in your own implementation of IProvider.GetFeaturesAsync (it could wrap an existing provider if you want to use that). In that case you could map the resolution to a level, like we do in tile layers. You would have about 20 different levels, for those levels you could cache the results of your algorithm.
