### ISSUE TITLE
Share code in MapControls

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#297]
The MapControls have had their individual development paths. They could share more code and be more consistent. This issue is meant to discuss the options.

### Single SharedMapControl
Since the MapControls are all derived from UI components they can not share a base class. Alternative:  Create a statefull SharedMapControl class which will be a member of all MapControl. All shared calls will be delegated to the SharedMapControl. Because there are a lot of event handlers they will need to be assigned to the SharedMapControl. This will still be quite some code, and will not be very clean. Maybe IL weaving could help here (I don't know that much about it). https://stackoverflow.com/questions/189359/what-is-il-weaving

### Several shared components
Also it could be possible to just share code in a number of special purpose classes. Like a class for all viewport manipulation.

### Viewport wrapper
MapControl now has a viewport member. Perhaps there should be a layer between that which takes case of map manipulation.

### Existing relevant code
- IMapControl
- SharedMapControl (static, not thought through).
- Viewport.

This post is just the get the thinking started, I have not spend proper time on this yet.

@radderz I read you already have some more code sharing outside of Mapsui. How does that work?

**Comment by radderz** [comment]
I think there are some other options here, partial class in a shared library project. The benefit here is the shared code just compiles directly as that class and doesn’t need to know about the inheritances. I.e you declare then partial class and platform specific base class in the platform specific project and you just declare then partial class with no subclasses in the shared project. Then you would be able to do any shared logic in the shared library where that logic takes in platform agnostic parameters. I.e should already have scales etc taken into account.

Another option would be default implementations in interfaces which is a new c# feature that will be release soon.

I use the first option currently as it just works without extra scaffolding.

**Comment by radderz** [comment]
I can provide you and example as a pull request if you’d like for the first one. I can move the shared touch code and all the shared properties into that partial class.

**Comment by charlenni** [comment]
The disadvantage is, that all other projects should be shared projects too.

**Comment by pauldendulk** [comment]
@radderz parial could be a good option. Do you have a public branch I could look at?

**Comment by pauldendulk** [comment]
Hmm, partial classes should be defined in the same assembly. So I don't see how that could work here. Since the MapControls themselves are (and should be) in separate assemblies. 

But apparently you have something working with partials. I am curious.

**Comment by charlenni** [comment]
Radderz talks about Partial classes in shared libraries.

**Comment by pauldendulk** [comment]
@charlenni In that case the Mapsui UI assemblies should have a reference to those shared libraries. Those shared libraries will be compiled as part of the UI assemblies, so, I would think for the user this will have no consequences. 

You say all others should be shared too. Why? could we not just add a Mapsui.Shared shared project? It should have a reference to the Mapsui PCL I guess. Could that work?

**Comment by charlenni** [comment]
You get at the end a platform dependent assembly, one for Android, one for iOS and so on. With such assemblies you couldn’t create a PCL like one for Xamarin.Forms. For a library PCL seems the better way.

**Comment by radderz** [comment]
Shared projects don’t have references, they are effectively just a way to link code files to multiple projects. As in the get the references of the project which has a reference to it on a per parent project basis. It is like have that file directly within the UI projects directly.

I’ll do an example when I get home, I am at a batch at the moment with no PC.

There is no negatives other than that you have some code in a separate file. You don’t end up with any extra classes or assemblies. Will still work the same with xamarin.forms. The only thing about shared libraries is that the apis need to be common on all the platforms otherwise you end up with the odd if #define occasionally.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by radderz** [comment]
In this case though the defines wouldn’t be needed as it would be part of a partial class so the platform specific parts are in the other halves of the class.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pauldendulk** [comment]
Did some tests. 
- Created a shared project Mapsui.UI.Shared with a partial MapControl in namespace Mapsui.UI
- For Mapsui.UI.Wpf added a reference to Mapsui.UI.Shared
- Changed the namespace for Mapsui.UI.Wpf to Mapsui.UI.
- It is now possible to put any code that is in shared MapControl. Easy to understand afterwards. It is basically the same class definition, just another file.

This is a great suggestion. I would not have come up with this on my own since I never use shared projects. Thanks.

The change of namespace is a breaking change that everyone will notice so this needs a major version increment.

**Comment by charlenni** [comment]
Argh, @radderz you are right, it would work. I was at the wrong place, I thought about Map, not MapControl. There it wouldn’t work. For MapControl it should work.

**Comment by radderz** [comment]
You could make it backward compatible by making a new map control class in the old platform specific name space that inherits this new namespaced shared map control. And just put an obsolete warning tag on it to say it will disappear on the next major version?

**Comment by pauldendulk** [comment]
@radderz That is possible but could also introduce namespace confusion. Perhaps we should just do a major release in the near future. 

or... also an option: #if the namespace of the shared MapControl like this:

```
#if ANDROID
namespace Mapsui.UI.Android
#elif IOS
namespace Mapsui.UI.iOS
#else
namespace Mapsui.UI.Wpf
```
So we could start work on it right now.

btw, obsoleting methods has been a problem for some users in the past. They compile they projects with 'treat warnings as erros' set. The obsolete method introduces a warning and thus a compile error for them. That is surprising if it is not a major version update. Annoying because I like the obsoleting as a way to move forward. We could 'obsolete' it just with comments though.

**Comment by charlenni** [comment]
I like the #if part for namespaces. It is easy to implement and should be made only at one place (shared MapControl).

But although a breaking change shouldn’t be a problem. Normally it should be possible to replace using a very fast.

**Comment by charlenni** [comment]
Btw. what things should be handled in MapControl?

**Comment by radderz** [comment]
I think that updating and having a namespace issue is pretty minor as most dev tools tell you the namespace that is missing and in error.

MapControl (platform side) should deal with all platform interactions and convert them into platform agnostic values to pass through to the MapControl (shared side). MapControl deals with all user interactions with the map and platform events like size changed, destruction of view etc. I think touch interaction makes sense in the control rather than the map as not all platforms have touch, but rather mouse clicks and these should be handled a little differently sometimes (like hover).

**Comment by pauldendulk** [comment]
It is minor but it is breaking and the #if solution is trivial.

**Comment by charlenni** [comment]
While I worked on the native MapControl for Forms I encountered some problems.

Up to now, each MapControl does different things. They combine platform specific things like touch and mouse events with handling of this. The OnSingleTapped event calls function to check for infos. I think, this should not be part of MapControl. MapControl should call a function of Map, which should than handle this.

So I would say, remove all things, that are not platform relevant from MapControl. 

And regarding the other issue: yes, fling and animated zoom would be great, but shouldn’t handled in MapControl.

**Comment by radderz** [comment]
The problem with that idea charlenni is that some modes of ui may be different enough that a generic way does work, i.e. mouse click doesn't have an equivalent in mobile. However we could do a matrix of what things are common and see if its worth moving just those to shared code within mapsui.

**Comment by charlenni** [comment]
But what does a mouse click? Isn’t a click not the same as a tap and should result in a SingleTapped or DoubleTapped? And the wheel is the same as a double click on the map and should result in a ZoomIn or ZoomOut event?

Take a look at the gesture handling of SkiaSharp. I used it for the Forms implementation. There is all you need, except the mouse wheel events of UWP. You could find this native implementation on [GitHub](https://github.com/charlenni/Mapsui/tree/Forms). Look at the MapControl in the Mapsui.UI.Forms folder.

**Comment by radderz** [comment]
They tend to get treated differently, I don't know why specifically. A Mouse also has multiple buttons so on form factors where a mouse makes sense it would limit functionality if we only cared about single tap/double tap. This doesn't impact me as I only care about the touch interactions and not mice but others might use the mouse clicks in different ways that we are unaware of.

**Comment by charlenni** [comment]
Ok, than there are OnSingleTapped and OnSingleClick. Wheres the problem? Map exposes some events and the author of the MapControl decides, which one to call for a event.

Or we could use the SkiaSharp event handling. Could be done for iOS, Android and UWP already. And should be possible for WPF too. See [here](https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKTouchEventArgs.cs).

**Comment by radderz** [comment]
At the moment WPF also has the XAML renderer, so unless that is going to be deprecated we can't use Skia event handling in WPF. 

If the map events have a tap type in the argument class, which could be something like touch, left mouse, right mouse and the number of clicks it could work the way you are suggesting?

**Comment by radderz** [comment]
@pauldendulk - What is the benifit of having the XAML renderer in WPF? Does it have additional capabilities like Line styles etc?

**Comment by charlenni** [comment]
In the native Forms implementation I mentioned above, I use only the touch event of SkiaSharp and generate single, double and multi taps by myself. This is possible. Although I created a VelocityTracker for fling, so that you get a velocity in x and y direction if you release the mouse button or lift the finger.

And it should be possible on WPF to get the same event as with SkiaSharp.

**Comment by charlenni** [comment]
I think, Paul mentioned some parts of drawing, that work only on WPF, but not with SkiaSharp. And because of backwards compatibility, WPF should persist.

**Comment by radderz** [comment]
Yes in the forms example you could use the touch events in the control and pass them to the map to do things, which would work fine for WPF, as you are just generalising the touches and sending them through.

For the skia native control for forms are you thinking of doing animation? As animation would be done wherever the touch handling is done, and if you want to handle the touch interactions in the map rather than the mapcontrol, you wouldn't have access to the forms animation classes.

**Comment by pauldendulk** [comment]
About Map versus MapControl. Initially the Map was meant to hold only the Viewport and the Layers. More functionality has moved into it, like the Info event, mainly because the Map is shared code. This is not a great motivation although sharing code is important. An another important factor is the user perspective. I think a user getting started sees Mapsui as just a MapControl like any other control, like a button. The user will look for events on the MapControl itself initially.

More reactions later.

**Comment by charlenni** [comment]
Ok, that is logic.

Here is a small discussion list:

1. With this in mind, I would say, that all events regarding interaction should handled by MapControl. This events could all be handled by user. If the user doesn't handle them, standard handling takes place, like check for Features on single tap or zoom for double tap. Up to now, I have the following events:
* ViewportInitialized
* TouchStarted
* TouchEnded
* TouchMoved
* Hovered
* Swiped
* Flinged
* SingleTapped
* LongTapped
* DoubleTapped
* Zoomed
Are there any other I missed?

1. Map doesn't know anything of the control. Up to now, you have, for example, the scale in the call of InvokeInfo. Map accepts only native map coordinates, no screen coordinates. If I'm correct, Viewport is the translater between screen and map positions. Ist this correct?

1. All code, which is usefull for more than one MapControl, exists in Map.UI.Shared project. I did this for the Forms branch.

**Comment by charlenni** [comment]
Today I expanded my Forms implementation. For this, I added a shared project (Mapsui.UI.Shared) and added it to Mapsui.UI.Forms. This is a start and could be added to other controls too.

Additionally I created a MapView component for Xamarin.Forms, derived from ContentView, where MapControl is in an AbsoluteLayout, so that other controls could be added. MapView should behave like the original one and to be easy to use. For this, it exposes a List of Pins with additionally PinClicked events. It's far from being ready, but it is a starter. Changed the sample to use this MapView instead of MapControl.

**Comment by radderz** [comment]
Hi charlenni, another option would be to make the functions that handle those instances in the map control virtual so the user can override/extend the functionality. I.e have a OnDoubleTapped function which is protected virtual rather than private. This would also allow the user of the library to setup the way bindings work for map features and interactions.

I think ideally for the first implementation of mapsui.forms you should not change too much in the way the existing structures work such that we keep them all consistant. Then we look how we can implement them in a more shared way.

**Comment by charlenni** [comment]
Oh, I didn't changed anything outside my project. I started the shared project, so other MapControls could use it.

Virtual functions could be a solution too. Up to now, I use events.

**Comment by radderz** [comment]
I mean if you do a pull request it would be a good starting point to be API/Interaction compatible with the existing MapControls without any changes in functionality. Then we can improve on the functionality across all the controls as we go. I would love a native xamarin.forms control that I could inherit and extend. 

Also, In xamarin forms its easy enough to layer things on top of others without using absolute layouts. You can put mutliple controls in a grid and have them layer overtop of eachother. I.e the map can span all the rows/columns and then the overlays be placed inside those columns/rows as required. So long as you put the map into the grid first it'll be behind everything else, this is how I did my layout I shared in the other issue.

**Comment by charlenni** [comment]
I uploaded it to my repository (see link above). I don‘t know, if Paul like to have this in the master.

I thought, that with AbsoluteLayout, MapView could provide some more functionality beyond the MapControl up to now.

**Comment by pauldendulk** [comment]
About 'scale' in InvokeInfo. The idea of the Info event was that it would return the original screen coordinates in the EventArgs. This allows the user to show a native popup at that location. So raw coordinates are passed into InvokeInfo and for correct calculations it needs the scale. Internally the InvokeInfo method uses the viewport which takes the scale-corrected coordinates. 

If the requirement to return the original coordinates is dropped you could pass in the scale-corrected coordinates. The method would be simpler. To show a native control the use could listen to the native touch event (the event that is on the base class of the MapControl), or the MapControl could expose the scale so the user could correct for it in the callback.

The fact that scale was an issue here became only apparent after the first implementation, so this was not thought trough much. There might be better ways. Ease for the user is an important requirement though. 

btw, the public InvokeInfo method is ugly. I think this is something that should be in the shared MapControl.

More reponses later. I intent to do some catch up later this week.

**Comment by charlenni** [comment]
Do you would suggest to use Grid instead of AbsoluteLayout? Even it is slower?

Do you think, it would be helpful to mimic Xamarin.Forms.Maps?

**Comment by radderz** [comment]
I don't think the Xamarin.Forms.Maps is very good so I don't know if mimicing that would be that useful, if absolutelayout is faster and you are happy to deal with the size changes etc then its all good, the grid way didn't work out as a performance issue on my apps so I never looked into using the absolute layout.

**Comment by charlenni** [comment]
@pauldendulk To come on with the shared project: what could I do to bring my changes into your master. Should I redo them on the master branch? Or should I create a pull request for the Forms part, which I have done up to now?

**Comment by charlenni** [comment]
I thought about Map, Viewport and MapControl and I‘m not sure, if I understand it correct.

Map holds all the data belonging to a map like layers, features and so on. Viewport defines the part of the map, that is visible to the user. It holds the center and extent and handles although all changes of them. MapControl than handle all events, which users make with the map and calls the renderer, when the map needs a redrawing. Is this correct? If yes, why than are functions like NavigateTo and RotateTo in Map and not in Viewport?

**Comment by radderz** [comment]
@charlenni for the navigateTo, I tend to directly edit the rotation/center/resolution values on the viewport itself instead of these functions, The only one that seems useful to that is to navigate to an extent and I thing this could be part of the viewport I guess.

As for the shared project I'll get started with it this week I think. I'll move all the generic parts of the touch interactions out of the main files. @charlenni , you could then do your changes based on this shared library as it'll give you a basis for consitancy with the others. The other option would be to import your changes for xamarin.forms and then make it consistant using the shared library.

**Comment by radderz** [comment]
@charlenni - for your xamarin.forms code, how responsive do you find the touch interatctions?

**Comment by charlenni** [comment]
I would like, if you could use the shared project I create. So it would be much easier for me :)

Responsiveness is good up to very good. You could test it. Samples for Android, iOS and Uwp are included. iOS is not tested up to now. Tomorrow?

**Comment by radderz** [comment]
@charlenni - sure I'll have a look at your implementation before I do anything, and if your implementation is close to what is needed I could just work on using that and do some testing/bugfix etc if required.

**Comment by pauldendulk** [comment]
There is now a shared MapControl project. More code could be move there but I see this will be continuous work as part of other work on the MapControls.
