### ISSUE TITLE
Event for map movement

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#398]
Hi,

I need catch when the map (envelope) is moving, size changing / zooming etc. by mouse (scroll, cursor) but not only (widget also).
But not RefreshGraphics, DataChanged, Info.

Which event on which object will be the best? (Map.PropertyChanged ?)

(if the issue was reported already, please url)

Thanks,
Łukasz

**Comment by pauldendulk** [comment]
You could listen to Viewport.Center property changed. 

Be aware that this called whenever the map is move and could cause performance issues if you do heavy calculations.

**Comment by pauldendulk** [comment]
Ah yes, charlennis ViewportChanged is indeed better.

**Comment by lukaszpitulski** [comment]
OK, thanks.
For now, I used Map.PropertyChanged  but  Map.Viewport.ViewportChanged looks the same (for the user).

BTW What with the events in Map.ViewChanged... ?

**Comment by lukaszpitulski** [comment]
Continuation in https://github.com/Mapsui/Mapsui/issues/399

**Comment by lehmannk** [comment]
I am having trouble with `Map.Viewport.ViewportChanged` Upon setting a new viewport with `MapControl.Navigator.NavigateTo` alone this event gets fired 6 times. When moving the mouse the slightes bit left / right / up / down this event also fires about 6 times. When zooming in and out the event fores about 30 times. This is a problem fopr me as I have to do some heavy calcs on viewport change. Maybe this is because of the animation effects when panning / zooming. Is there a way to receive events on when the viewport has settled?

**Comment by charlenni** [comment]
Do you suggest a new event or would a flag set when called, like `Animation=true` be enough?

**Comment by charlenni** [comment]
BTW. would be better to open a new issue than using this old closed one.

**Comment by lehmannk** [comment]
Hi @charlenni thanks so much for your quicke response. Yes, I believe a flag in `PropertyChangedEventArgs` would be enough. Do you want me to open a new issue for that?

**Comment by charlenni** [comment]
That would be good. I try to look into this.

By the way, do you use the AnimatedNavigator?

**Comment by lehmannk** [comment]
new issue created (#927)
And no, I am just using the default Navigator. Until now I didn't even know that there is such thing as an `AnimatedNavigator`. Will try this one too. Thanks a lot for supporting this :-)
