### ISSUE TITLE
Zoom limits

### ISSUE THREAD

**Issue by lukaszpitulski** [Mapsui/Mapsui#416]
Hi folks,
(if the case was already please send me there, thanks)

Are any limits for the zooming of the map in Mapsui?
What I have here now is max zoom level 19 (Scale = 1:1065), and I need 24 (1:33).

I tried:
Map.ZoomLimits = new MinMax(1, 24); 
but, this gives me some weird view

What should be in MinMax? (documentation pleeeaaaaassssse ;) )

I tried also:
MinMax(-100, 20000)
MinMax(-1000, 50000)
etc.
but still max zoom is too small (is not enough close, not enough details I can see on the map).
(in Map.ZoomLimits  Max is MinZOOM and Min is MaxZOOM I think :| )

I'm not sure if this what I can see in GeoServer (OSM maps) is true or graphic fake zoom. In GS I can zoom till scale = 1:2.

And how about ZoomMode in that issue?

Thanks for the help!
Łukasz

P.S.
Level values based on ThinkGeo zoom levels, Scale from GeoServer

**Comment by pauldendulk** [comment]
About min and max. These refer to the values used. Since these values are in units-by-pixel and not pixel-by-unit this could be counter intuitive.

As @charlenni said, the baselayer determines the number of levels. So if you use a baselayer with more levels this is solved. 

You can create a baselayer with more zoomlevel through the constructor of the schema. The 'GlobalSphericalMercator(0, 22)' below.

```c#
        private static HttpTileSource CreateTileSource()
        {
            return new HttpTileSource(new GlobalSphericalMercator(0, 22),
                "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                new[] { "a", "b", "c" }, name: "OpenStreetMap",
                attribution: OpenStreetMapAttribution);
        }
```

In this sample the tilelayer will try to do requests to levels that do not exist, which is awkward (but works for the end user), but if you have a tile source with more levels this will have the proper effect.

**Comment by pauldendulk** [comment]
If you use a proper wmts you can initialize the baselayer with the metadata and you don't have to do anything special for it. I will send you a sample.

**Comment by lukaszpitulski** [comment]
🥇 
WMTS is the solution.
Thanks!
