### ISSUE TITLE
UWP high CPU/GPU while doing *NOTHING*

### ISSUE THREAD

**Issue by jasells** [Mapsui/Mapsui#429]
The subject says it all, really.  I think I do have a solution, but my fork is a little our of date.  Going to get your latest updates and issue a pull req in the next few days.   The current fix is for UWP only, but likely is similar on WPF, and takes CPU ~ 5-6% and GPU of 12-15% @ idle on a Surface Pro (core i7 7660U with Intel Iris Plus 640) to 0% CPU and 0% GPU *unless* the screen actually changes (zoom, pan, etc) @ 2.5-3% CPU and 6% max GPU.  

Debugger attached while making those measurements.

I have a couple of Task Man screen shots I'll post ASAP.

**Comment by jasells** [comment]
Here is [link ](https://1drv.ms/u/s!AkJlaLtUNZiihLMSk4nN3McLsXR0Yw) to TaskManager screen-shot with current build. <br>

Here is [link](https://1drv.ms/u/s!AkJlaLtUNZiihLMRaKwrhXMsRkpPbA) to TaskManager screen-shot after fix.

**Comment by charlenni** [comment]
Would be nice to know, where the problem is. Any hint?

**Comment by jasells** [comment]
It is in the UWP [MapControl.cs](https://github.com/jasells/Mapsui/blob/1.4/Mapsui.UI.Uwp/MapControl.cs) mostly.  The current impl relies on CompositionTarget.Rendering event to make sure screen re-draws occur during drags.  This event is *not* on-demand, so it ends up doing a *lot* of redraws, even when nothing on screen has changed.
<br><br>
There a couple of ways to make it more on-demand/event driven vs. constant re-draw.  Looking into which is best and how to branch/make pull request.  Been a while since I did that on GitHub.

<br><br>


I also found an issue when removing a layer didn't refresh the map until the map was moved or NavigateTo was called (i.e. some other event caused a re-draw, not layer remove).

**Comment by pauldendulk** [comment]
Wrapping this up. What I did not see at first is how the GPU was high while the Mapsui renderer was not called. This was because _renderTarget.Invalidate() not only triggers the paint event but also does a repaint of the current state of the skia canvas, even if not changed. The reason GPU was not high in WPF is that there was an _invalid check in CompositionTarget_Rendering itself (I was only focused on the paint method.

In UWP:
```
        private void CompositionTarget_Rendering(object sender, object e)
        {
            _renderTarget.Invalidate();
        }
```

In WPF:
```
        private void CompositionTargetRendering(object sender, EventArgs e)
        {
            if (!_invalid) return; // Don't render when nothing has changed

            if (RenderMode == RenderMode.Wpf) RenderWpf();
            else SkiaCanvas.InvalidateVisual();
        }
```

**Comment by pauldendulk** [comment]
I will investigate if it is possible to use the same logic in WPF. It is a bit different because there is also WPF rendering. The CompositionTarget_Rendering logic still stems from the Silverlight days, there is probably a better solution now.

An additional advantage of removing CompositionTarget_Rendering is that I don't have the dispose problem that forced me to write the weak reference construction.

**Comment by jasells** [comment]
I'm glad you were able to simplify things.  I figured that CompositionTarget_Rendering event was pulled from WPF and not exactly the way UWP was intended, but I had not dug into WPF.


>  _renderTarget.Invalidate() not only triggers the paint event but also doesa repaint of the current state of the skia canvas, even if not changed

.

exactly.  I probably was way too complicated in my explanation.  =)
