### ISSUE TITLE
Map with picture file color image with opacity

### ISSUE THREAD

**Issue by Wil69** [Mapsui/Mapsui#489]
Hi,

I would like to know if it's possible to add above the map a png file containing colors with opacity (atmospheric index). And to be able to zoom together ?
How I can to do that ?
Thks

**Comment by pauldendulk** [comment]
zoom together? what is that?

So, the png file is really outside of the map. You click somewhere on the png and then something should happen in the map? What should happen?

**Comment by pauldendulk** [comment]
This is what is happening when using WMS. You have to create a Raster geometry which has a boundingbox in world coordinates.

**Comment by pauldendulk** [comment]
https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Geometries/Raster.cs

The constructor takes a MemoryStream, which is the data of you image, and a BoudingBox, which is the extent of the image. Add the raster to a MemoryLayer. Not too hard.

**Comment by pauldendulk** [comment]
If your map is in SphericalMercator make sure you transform the coordinates of the BoundingBox to SphericalMercator.

**Comment by Wil69** [comment]
Ok thank you for your feed back. We will try that !

**Comment by Wil69** [comment]
@pauldendulk We try this code : 
var image = new MemoryStream(await DownloadImageAsync(_url));
            var raster = new Raster(image, new BoundingBox(230000, 5510000, 800000, 5866000));
            var layer = new MemoryLayer() { DataSource = new MemoryProvider(raster)/*, Opacity = 0.75*/ };
            _map.NativeMap.Layers.Add(layer); [

That works well but when we add Opacity the map it's very very slow.
 
What do you think ?

**Comment by pauldendulk** [comment]
Probably because the image is too big. This means you need a more advanced solution where you use the image layer and cut out of part of the image when you fetch the data. I think you will need to write your own Provider (DataSource). Something like the WmsProvider. It will have the image in memory. On the GetFeaturesInView of the provider you will need to do some re-sampling of the image. Not very easy (but fun to do). You could use SkiaSharp there.

**Comment by Wil69** [comment]
ok thank you. See you later.
