### ISSUE TITLE
Widget with SVG

### ISSUE THREAD

**Issue by antunesl** [Mapsui/Mapsui#548]
I was trying to create a widget with the purpose of indicating the center of the map, always fixed with some transparency, so that the user can see underneath.
Is there a way to render a widget loading the content from an svg? I was trying to refer to the documentation and examples, but at this point I'm not able to create a custom render for a widget.
Is it Widgets my best approach to this problem?

Thanks

**Comment by antunesl** [comment]
Sorry for the lack of info, I was really trying to validate if widgets were the best approach.
I'm currently using Mapsui for Xamarin (1.4.7), with Skia renderer.

**Comment by charlenni** [comment]
What you want is implemented in Mapsui 1.4.8 as CenterCross widget (see [here](https://github.com/Mapsui/Mapsui/blob/1.4/Mapsui/Widgets/CenterCross/CenterCrossWidget.cs) for common implementation and [here](https://github.com/Mapsui/Mapsui/blob/1.4/Mapsui.Rendering.Skia-PCL/CenterCrossWidgetRenderer.cs) respectively [here](https://github.com/Mapsui/Mapsui/blob/1.4/Mapsui.Rendering.Xaml/CenterCrossWidgetRenderer.cs) for the renderers). The only difference is, that this widget only draws a simple cross in the center of the Mapsui view. But it should be easy to expand this widget, so that any SVG image could be drawn instead of the cross.

Btw. saw, that the comment for the widget is completely wrong. It is copied from the scale bar widget :D

**Comment by antunesl** [comment]
Thanks @charlenni, I have already been able to use this widget on the map, I will now extend it to be able to change the visual part of it, I'm going to the SVG image.
Thanks for the help.

**Comment by antunesl** [comment]
@charlenni There is a way to add my custom renderer to the WidgetRenderer in v1.4.8?
I see that in master branch the [WidgetRenderer ](https://github.com/Mapsui/Mapsui/blob/37641409a33617b20475a6d58f76e4bbd19fbc38/Mapsui.Rendering.Skia/SkiaWidgets/WidgetRenderer.cs) loads the renderers by type, but I'm not seeing how I can in v1.4.8 add my custom renderer.

**Comment by charlenni** [comment]
You couldn't do this with 1.4.8. In this version, the widget renderers are hard coded. You have to change Mapsui. You must make a PR for this.

With version 2.0 of Mapsui you could create your own widget, which than could have its own renderer.

**Comment by antunesl** [comment]
Yes that's what I thought, I'll probably wait for version 2.0.
Thanks @charlenni
