### ISSUE TITLE
Read a shapefile or kml file and display it on the map

### ISSUE THREAD

**Issue by cpalominoch** [Mapsui/Mapsui#574]
Hello, how are you?
Please have a query: Does the mapsui control for xamarin read a shapefile or kml file and display it on the map?

**Comment by charlenni** [comment]
Did you looked at the [shape file sample](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common.Desktop/ShapefileSample.cs)?

**Comment by cpalominoch** [comment]
Thanks for the information, but the example is for winform. Is there an example for xamarin?

**Comment by charlenni** [comment]
@cpalominochch Mapsui doesn't work with WinForms.

I assume, that the ShapeFile is in namespace Mapsui.Desktop, because there are many file operations used. So I would take Mapsui.Desktop.ShapeFile and use it as base for an own implementation. I think, that you could use the file operations with .Net Standard 2.0 on all platforms.

If you succed, it would be nice, if you could make a PR for the code.

**Comment by pauldendulk** [comment]
There is no built in support for kml. I did work with kml in Mapsui in a project before. There are kml open source libraries available. You have to implement a kml datasource.

For shapefile there is only the desktop sample. It does not work with Xamarin. You could try to port it to .NET Standard 2.0, not sure how hard that is. You could also search for a cross platform shapefile reader and implement your own datasource.
