### ISSUE TITLE
BoundingBox Touches

### ISSUE THREAD

**Issue by pauma23** [Mapsui/Mapsui#613]
Hello,

why does `Touches` return false when edges of two boundingBoxes are on same edge. Example upper edge of first box is 1 and lower edge of second box is also at 1:
```csharp
BoundingBox b1 = new BoundingBox(0, 0, 1, 1);
BoundingBox b2 = new BoundingBox(0, 1, 1, 2);
bool touch = b1.Touches(b2);// return false
```

Best reguards,
Pauli

**Comment by pauldendulk** [comment]
This is old code inherited from SharpMap. It will at some point probably be replace by the NTS library. 

I will change it to fit the intuitively expected behavior.

The definitions of OGC spatial operations are sometimes not very intuitive. I will not dig into that right now. For those who are interested below is a part of the OGC simple feature specification on 'Touches'.

![image](https://user-images.githubusercontent.com/963462/53432281-7d62b300-39f2-11e9-993a-ef1f65ede3a3.png)

Source: https://www.opengeospatial.org/standards/sfa
