### ISSUE TITLE
Shapefile example 

### ISSUE THREAD

**Issue by isra60** [Mapsui/Mapsui#632]
I'm trying to use Shapefile layer (Raster Layer) with other layers, like TileLayer. 

Maybe I missign something but the in Shapefile Layer seem to not have Resolutions and also the image to location function always gives locations around the 0,0 Lat Lon

**Comment by pauldendulk** [comment]
The Shapefile sample uses a RasterizingLayer. See CreateMap.

```c#
map.Layers.Add(new RasterizingLayer(CreateCountryLayer(countrySource)));
```
It created a raster for whichever viewport is selected. Similar to the ImageLayer used for WMS. The advantage is better performance. A problem with the current implementation is that map info does not work properly. The info of the raster is returned instead of the underlying features.

If you remove the RasterizingLayer it will draw the separate features and feature info should work properly.

I think the original data is in the WGS84 coordinate system and not in SphericalMercator as most other samples. That would explain values near 0,0.

The ImageLayer does not use resolutions like a TileLayer. It might not be very hard to use the Shapefile provider as data source for a TileLayer.

**Comment by pauldendulk** [comment]
But I am not sure what you are trying. Did you wrap the TileLayer in a RasterizingLayer? Why?

**Comment by pauldendulk** [comment]
Keep the TileLayer separate. Make the shapefile faster with the RasterizationLayer. If you need coordinate transformation you could create a custom provider that wraps the shapefile provider and does the transformation. There are classes in Mapsui for transformation between spherical mercator and wgs84.

MapInfo will be problem with the RasterizationLayer. You need a workaround. Perhaps use an invisible Shapefile layer for map info.

**Comment by 88madri** [comment]
So. I have been looking into this...
For example the countries.shp has a bounding box of {-180,-89.9 180,83.5960388183594}. 
Something normal becouse is the world map in WGS84. And the created layer has a Envelope of the same size. 
I could implement something to check for the CRS of the Map and then obtain the proper locataion of that mouse point.

But I don't know exactly how to work with the two layers at the same time. The MbTile Tile Layer with world units in web mercator... which the Envelope would be around WGS84 {-20037508.342789,-20037508.342789 20037508.342789,20037508.342789}
and the countries shapefile layer with an envelope of {-180,-89.9 180,83.5960388183594}.

One will be much small than the other... 
How Can I change that envelope?

**Comment by 88madri** [comment]
So Finally I make progress with this.. This is my solution with WGS84 shapefiles.

`
var countrySource = new ShapeFile(GetAppDir() + "\\GeoData\\World\\countries.shp", true) {CRS = "EPSG:4326" };

map.Layers.Add(new RasterizingLayer(CreateCountryLayer(countrySource)));

private static ILayer CreateCountryLayer(IProvider countrySource)
        {
            return new Layer
            {
                Name = "Countries",
                DataSource = countrySource,
                Style = CreateCountryTheme(),
                CRS = "EPSG:3857",
                Transformation = new MinimalTransformation()
            };
        }`

So the Layer added to RasterizeLayer is a common layer with  CRS = "EPSG:3857" an its datasource is a shapefile with CRS = "EPSG:4326". Then the shapefile is reprojected to WebMercator.

Also is possible to create a VectorLayer like OpenGis to open a shapefile instead of use a Rasterizing Layer?

**Comment by spaddlewit** [comment]
Yes, just remove the 'new RasterizingLayer()' part and feed the CreateCountyLayer results right into map.Layers.Add
