### ISSUE TITLE
get elements around click

### ISSUE THREAD

**Issue by sebs78** [Mapsui/Mapsui#665]
Hi,
Is it a way to have the list of elements around a touch click in the map? 
I have a map with a lot of elements on different layers and because it is not always possible to select the good objet when objects are near, I would like to show a list of elements under the click.

Regards
Seb

**Comment by mbaker92** [comment]
You could get the features on each layer currently in view and check each feature to see if it is within some margin of the click event. This [link](https://github.com/Mapsui/Mapsui/issues/572) to an issue I had with the margin of a bounding box has some code you could modify to fit your needs.

The `var features = mapControl.Map.InfoLayers[0]`  line can probably be changed to iterate through all the InfoLayers you have so that you can get all the features. 

The `Boundingbox.Distance(new Point(args.WorldPosition.X, args.WorldPosition.Y)) <= marginworld)`  if statement can be used to determine if the feature is close enough and then you could store that feature in a list and display it to the user.

**Comment by pauldendulk** [comment]
Thanks @mbaker92!

For further inspiration look at the current implementation of feature info.
