### ISSUE TITLE
Store tiles locally for later offline use

### ISSUE THREAD

**Issue by FrankPohl** [Mapsui/Mapsui#669]
Hello,
I can't find out how to implement a desired scenario for my app.
I'm pretty sure that it is possible but I'm not able to put all the information I found correctly together.
So it would be great if someone can give me some hints for my scenario. Here it is:
I would like to store all the tiles that the user has loaded in the app and later use these stored tiles in the app but also be able to transfer them to a mobile phone. 
I know that there is some sort of caching but I haven't found how I can use this for my purpose.
If he is doing this in an app on a desktop computer, he should be able to transfer the stored tiles via file transferred to a mobile phone (Andorid with Xamarin.Forms App) that is connected via USB.
The phone app should be able to use these locally stored tiles first and if there is no tile available locally, it should try to download it from the tile server.
Would appreciate any ideas on that.

Frank

**Comment by charlenni** [comment]
You could save them to a MBTiles file, which is a SQLite database. Than you could use this file for your offline use.

**Comment by FrankPohl** [comment]
I have seen the sampel for doing this, but is there some sample for saving all tiles I have loaded from the web to an MBTiles file? 
I haven't found any, so the question is how can I can I fill the MBtiles file? 
But I have also one more Question for reading from the MBtiles file. How do I recognize if a tile is not part of the MBtiles file? Is something like a NoTileFound event raised?

**Comment by charlenni** [comment]
Mapsui uses BruTiles for accessing MBTiles files. [There](https://github.com/BruTile/BruTile/blob/950c4d8768e013621bfb68573be45abe65665714/BruTile.MbTiles/MbTilesTileSource.cs#L159) you could see, that the TileSource returns null for a missing tile, otherwise it returns the byte array for the tiles image.

There isn’t any special code for writing the MBTiles. Because it is a normal SQLite database with only a few tables, you could do it by your own. But be careful: respect the copyright of the tiles.

**Comment by FrankPohl** [comment]
Thanks for the info. This is sufficient for me to go on.
