### ISSUE TITLE
[question] Would it be possible to project rasterized layers?

### ISSUE THREAD

**Issue by garykindel** [Mapsui/Mapsui#721]
My application uses Mapsui to build maps with shapefile layers.  Shapefiles have their performance challenges.  I like the approach to rasterize the a shapefile but I need to project it similar to a vectorlayer.  How much work would it take to add projection support to  rasterized layers?  I would be willing to take on this feature but I need some direction.  Thanks.

**Comment by pauldendulk** [comment]
I think there was an issue with this. In theorie it should be possible to project the shapefiles first so you don't have to project the rasters. I believe in practice the problem is that the rasterlayer gets the ITransformation set by the map while the vectorlayer behind it needs it. 

I guess it should be possible to do some projection in code on the datasource to circumvent this.
