### ISSUE TITLE
[Improvement] Using DotSpatial.Projection.NetStandard to improve projection implementation

### ISSUE THREAD

**Issue by antoineloos** [Mapsui/Mapsui#737]
Hi @pauldendulk, 
I recently try to work with a very specific projection and sadly it was not supported by the library that you mention on the documentation (ProjNet4GeoAPI) for some specific projection like Lambert1 for exemple. Then I found DotSpatial projection Library and someone has made a NetStandard project that contain only Projection system with a full support for all EPSG projection and also some nice method to import proj4 format projection string. 
[https://github.com/ststeiger/DotSpatial](https://github.com/ststeiger/DotSpatial)

It's work very well with a custom implementation of ITransformation on Mapsui. 

So are you agree if I make a sample project that I'll sent it to you to demonstrate that ? 

Best regards

**Comment by pauldendulk** [comment]
I know the original DotSpatial project but have not followed how they progressed. If I understand correctly this project is a fork? It is a fork the projections project only? Is there no dependency on the DotSpatial geometries?

**Comment by pauldendulk** [comment]
It mentions:

> DotSpatial.Serialization and DotSpatial.Positioning uses System.Drawing so they does not work on Android/iOS

But you develop for Android right? Was this not a problem for you?

**Comment by antoineloos** [comment]
In fact there are three project on the repo and the projection project does not have any dependency to System.Drawing. So i have already test it on an Android project, it's work well. The nuget package contains only Projection library.

**Comment by pauldendulk** [comment]
At this point I don't want to add a nuget dependency on this project. It's status is uncertain since it is a fork and still young. Also alternative libraries might be used in the future. 

I would welcome a tutorial page on how to use it. This could be a page under 'How things work' or perhaps we should introduce a 'Tutorial' section. A PR for this would consist of a new page in [this folder](https://github.com/Mapsui/Mapsui/tree/master/docfx/documentation) and an extra entry to toc.md. When merged this will be automatically deployed to mapsui.com.

On the basis of this tutorial we could perhaps make code improvement to make it easier to use such a library. We perhaps we could even introduce a new nuget package which makes attaching the library to nuget easy. This would be a Mapsui.DotSpatial.Projection package which as a dependency on the DotSpatial.Projections package and has some code to glue the two together.

**Comment by pauldendulk** [comment]
Projections with DotSpatial.Projection  was implemented. It is part of the Mapsui.Extensions nuget.
