### ISSUE TITLE
OSGB (EPSG:27700) tileset

### ISSUE THREAD

**Issue by fusionconsulting** [Mapsui/Mapsui#813]
How would I go about loading a tileset for EPSG:27700? I have now converted my map tiles based on OSGB coordinates with a bounding box of 0, 0, 700000, 13000000. which produces a grid of 147 columns (0-146) and 273 rows (0-272), each tile at 256 pixels.

I've loaded this into Mapsui as a tile source but it's requesting tiles way outside the range which is I believe is down to EPSG:27700 not being supported and using EPSG:3857 coordinates.

Do I need a transform or a schema to use the OSGB bounding box and tile grid? I'm a bit confused as to what the correct approach is for loading a coordinate system outside of lat/lng.

**Comment by pauldendulk** [comment]
Side note: One thing you need to know is that the openstreetmap baselayer that is used in many samples can not be combined with a layer in EPSG:27700. This does not have to be problem. You could use Mapsui in combination with another baselayer in the same projection. (Except for the MapView which is tied to EPSG:3857).

If the tiles are fetched that are not available in the mbtiles file this means the mbtiles file is incorrect. The metadata publishing information about the schema does not match the content of the tiles. 

Now, I am happy to tell you that Mapsui is very flexible and could correct the error the mbtiles file by overriding the incorrect metadata with a tileschema in code, but a problem you have is that you do not know what the correct schema is. Since you created the mbtiles file yourself the best strategy is to fix the error in the source. Fix the mbtiles file. Perhaps the best approach is to load the mbtiles in some other tool (qgis probably has some support for this, perhaps using plugins) and make sure it shows correctly in there. If not, go back to your script. Look at the metadata table and try to understand it. Open other mbtiles files to see how metadata is specified there. Read the mbtiles and tms specifications to understand what the metadata should look like.

**Comment by pauldendulk** [comment]
Also according to the official spec mbtiles is always in EPSG:3857. For Mapsui this is no requirement but to make it easy for yourself it might be better to stick to EPSG:3857. But if your source data is not in EPSG:3857 this might be hard. Do you know which EPSG is used in your source data?

**Comment by charlenni** [comment]
If I understand @fusionconsulting correct, he uses [EPSG:27700](https://epsg.io/27700) for his mbtiles file.

@fusionconsulting You don't say, how you created the mbtiles file. You don't deliver any screenshots nor an example to try this. There might be a solution, but without any information, it is hard to solve.

First of all, did you checked, if the projection of the EPSG:27700 and the [EPSG:3857](https://epsg.io/3857) is the same? If not, than it would be logically impossible in Mapsui to show both tiles in the same map (@pau Is this correct?). For an explenation see [this page](https://openlayers.org/en/latest/doc/tutorials/raster-reprojection.html).

**Comment by fusionconsulting** [comment]
Sorry, I realise the information is lacking. I'm trying to work out what information is relevant to the problem. I'm new to mapping and not sure what's relevant and what's not.

So, I have a series of TIF images and related TAB data files which is in EPSG:27700 format. I can quite happily work with only using EPSG:27700 without having to mix the coordinate systems if I can get the map to display correctly.

It seems to me that MBtiles requires the data to be in EPSG:3857 format for the metadata, which I can translate where necessary for bounds etc but the tiles do not align to the map tile service specification as is required by MBtiles. 

I think I need to reproject the tiles onto a an EPSG:3857 coordinate system and then use that as the source for the MBtiles but I need to automate this process. Are there any open source tools that can help with reprojecting the tiles and/or conversion to MBtiles?

**Comment by charlenni** [comment]
As you can see in the above mentioned example, the tiles in EPSG:27700 format are not quadratic in relation to EPSG:3857. If you than transform your TIFFs to a quadratic view, you streets in the north will be wider than the streets in the south. So this wouldn't work. The only thing I see, that you could do, is to display your TIFFs without any other map tiles.

Btw. could you provide any of your TIFFs, so that we can see, how they look?

**Comment by fusionconsulting** [comment]
I'm happy to display the TIFs without any other map tiles, that would be perfect. I only need to display some overlay icons so matching an underlying map would not be a requirement. If I can display the existing content in the EPSG:27700 grid that would work fine. Can that be done with Mapsui? I can export the grid as necessary into the MBtiles file which would obviously not conform to the MBtiles specification but if it can work then that would be great.

I may not be able to provide a TIF as they belong to my client and I would need to get permission to upload them. I know that's not particularly helpful!

**Comment by charlenni** [comment]
Did you looked on the above mentioned example? It is exactly your case. Below "How it works" you see your TIFFs on the right side. They are all quadratic in their coordinate system. If you now transfer your TIFFs to a EPSG:3857 map, you see, that your quadratic TIFFs should be transformed to something like trapezes. So it isn't enough, to move your TIFF to a special position, but you have to deform them. 

Perhaps OpenLayers could do this.

**Comment by fusionconsulting** [comment]
Is it possible to use Mapsui to display a purely flat grid of tiles? This is going to be used for a very small restricted area and so reprojection would not be necessary if I could just display the existing tile grid.

**Comment by charlenni** [comment]
> 
> 
> I'm happy to display the TIFs without any other map tiles, that would be perfect. I only need to display some overlay icons so matching an underlying map would not be a requirement. If I can display the existing content in the EPSG:27700 grid that would work fine. Can that be done with Mapsui? I can export the grid as necessary into the MBtiles file which would obviously not conform to the MBtiles specification but if it can work then that would be great.

The problem is, that you don't have a correct MBTile file. This is, as @pauldendulk mentioned, always in EPSG:3857 format. What you could do is to create an own IProvider. This fetches raster images for a given BoundingBox in Mapsui coordinate format. You could convert the BoundingBox to your own coordinate system and than return your own image.

> I may not be able to provide a TIF as they belong to my client and I would need to get permission to upload them. I know that's not particularly helpful!

Ok, than this now clear.

> Is it possible to use Mapsui to display a purely flat grid of tiles? This is going to be used for a very small restricted area and so reprojection would not be necessary if I could just display the existing tile grid.

That should be possible. See the above.

**Comment by fusionconsulting** [comment]
Thanks, so I need to be looking at an IProvider. I will dig into that and see if I can use it in the way I need. Thanks for the clarification.

**Comment by fusionconsulting** [comment]
Is there any documentation on the IProvider interface? Where would I consume a provider?

**Comment by pauldendulk** [comment]
Some more pointers. 

### EPSG:3857
There is an mbtiles overlay sample that you can look at. It uses the torrejon-de-ardoz.mbtiles file. If you open it you will see a metadata table with an extent in EPSG:4326 (LatLon/WGS84/GPS coordinates). This is enough if your data is in EPSG:3857. To achieve this you will need to do a transformation of your raster.This is technically possible but I am not aware of any tools to do this. It will make the image uglier and will not result in a square area (but, this does not have to be a problem).
![image](https://user-images.githubusercontent.com/963462/74413562-ecbdf680-4e3f-11ea-9a9f-1b16cdd0bf4f.png).

### EPSG:27700
What I missed in my earlier remarks is that the metadata will always be transformed from EPSG:4326  to EPSG:3857 by the mbtiles tile provider, [see](https://github.com/BruTile/BruTile/blob/master/BruTile.MbTiles/MbTilesTileSource.cs#L125). So this will result in the wrong coordinates if you use EPSG:27700. In this case you will need to override the tile schema in code. In code the extend needs to be in EPSG:27700 coordinates, but you also need to get the offset and layers right. For this you need to know what you are doing. This is not something I can explain here. 

Perhaps it helps if you look at the [BruTile source code](https://github.com/BruTile/BruTile) to understand how things works.
