### ISSUE TITLE
Struggling with slow rendering of LineString [Forms]

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#860]
As my maps in my hiking app gets bigger and more "complicated", I am struggling with the speed of the rendering of the maps in Mapsui.

I have a map with a LineString containing 70k points, and when it tries to render that MemoryLayer its like the entire app "hangs" for many, many seconds - I cannot move the map, I cannot click - nothing.

When the engine/background task has finished - the map can then be moved, although very slowly.

So the question is - am I doing something wrong, or have I just reached a limit on a map with 70k points on a linestring (its actually several LineStrings, with a total of 70k points).

Fun fact : If I move away from there area containing my 70k LineStrings, the map movement is back to normal speeds!

I have recorded a video of it here : https://youtu.be/MQvxEb5c2XY

We have had this discussion before briefly, but now it has come to a limit where its a showstopper for me and speeds are no way acceptable anymore!

(Im on newest beta 37 of MapsUI)

**Comment by charlenni** [comment]
Would it be posible to get a small repo for this? Only a map with the LineString, so we could test it?

**Comment by tonyfonager** [comment]
I cannot ship you my app project, but let me see if I can create a new simple repo with the same issues.

**Comment by charlenni** [comment]
Would be enough. So we could play around and look, where the problems.

**Comment by tonyfonager** [comment]
I have a repo ready now - as it contains "private data" from my app, I would prefer if I could send it to you privately, instead of sharing URL here ?

You can PM me with an email address!

**Comment by pauldendulk** [comment]
pauldendulk@gmail.com

**Comment by tonyfonager** [comment]
Its sent via email to you now @pauldendulk

**Comment by pauldendulk** [comment]
Thanks! I could run the sample and reproduce the problem. A practical thing you could do right now is to wrap it in a RasterizingLayer. See the bottom two lines below:

```csharp
// create MemoryLayer with polylines
ml = new Layer("Routes");
ml.DataSource = mp;
ml.MinVisible = GetZoomResolution(20);
ml.MaxVisible = GetZoomResolution(8); // make the route layer visible from zoom level 8 -> 20
ml.Tag = "RoutesLayer";
ml.Style = null;
ml.IsMapInfoLayer = true;
var rasterizingLayer = new RasterizingLayer(ml);
map.Layers.Add(rasterizingLayer);    
```
Performance is back to normal again. There is an issue however with MapInfo in the RasterizingLayer. The feature inside that layer is now a bitmap which can not give you information about a specific feature. This is something I still need to look into. 

Another issue with the RasterizingLayer is projection, but you do not have this problem because your source data is converted to spherical mercator.

I also have been thinking about others solutions in the past but never got around to building them. They sound fancy but may not be very hard to create. 
- One is a RasterizingTileLayer. It rasterizes the features on the fly (like the RasterizingLayer) and puts them in a tile piramide. This will have a better performance, but actually the RasterizingLayer performs okay.
- Another is to create such a piramide (on the fly) but not with bitmaps but with features. Those features need to be simplified towards the top of the piramide. With this solution it would still be possible to get feature info. A challenge is how to simplify the features.

**Comment by charlenni** [comment]
But what is the problem? The number of points?

**Comment by pauldendulk** [comment]
> But what is the problem? The number of points?

ah, good point. Don't just fix things. Understand why. I kind of assumed it was. 70.000 sounds like a lot, but I did not check anything.

**Comment by pauldendulk** [comment]
I added a 'Many Vertices' sample under 'Special'. Simplified versions. Just a lot of points in one straight line. In Sweden, so it is almost real. 

With 10.000 points is quite okay on my Android device.

With 70.000 it is noticeably slow. 

What is weird is that it becomes slower if you zoom out. Even though initially all points were in view. This is also the case with 10000. The app even becomes totally unresponsive.

**Comment by pauldendulk** [comment]
I do not see this behavior on WPF.

**Comment by tonyfonager** [comment]
Paul, thanks for looking into this - I tried changing it to a rasterizing layer, which for sure performed better - but now I have lost my "click" function, which I certainly need to highlight routes on the map.

Also, why is it that those layers are first "painted" after you move AND release the finger ?

So when I move the map, by putting my finger most left side of the screen and drag it all the way to the right - as I do that, the parts of the route that should become visible is not painted - first when I release the finger, it gets updated and painted to the screen.

**Comment by tonyfonager** [comment]
> But what is the problem? The number of points?

It certainly looks like its down to the maximum number of point in one or more LineStrings.

But I was under the impression, that it was only the number of visible points at the screen at the same time, that would be an issue ?

So, even if you have 70000 points, if only 100 is visible in the current zoom resolution - it would not be an issue.

**Comment by pauldendulk** [comment]
> So, even if you have 70000 points, if only 100 is visible in the current zoom resolution - it would not be an issue.

Well you have many points in a single feature. This is problem for many geospatial solutions. Suppose you put this kind of data in a geo-database, it would consist of about 70 records, which individually would have around 10.000 vertices. Geospatial intersections would have to be calculated on 10.000 vertices. This will be slow. Spatial indexes won't help.

In Mapsui we draw a feature as a single thing. So all 10.000 vertices. If they were 10.000 points in separate features it would be different. In that case only the visible features will be drawn. So cutting large features up in to smaller is parts could help, and is often a necessity. In my suggestions above perhaps it would be possible to do this cutting up for you.

**Comment by pauldendulk** [comment]
About this click function. As I mentioned above I understand this is a problem. Perhaps this can be fixed somehow. Have to look into that.

**Comment by pauldendulk** [comment]
But apart from all that we now have a new problem. Mapsui comes to a halt if you zoom out on Android with even 10.000 points. This is really really weird since at the start all vertices are already shown.

**Comment by tonyfonager** [comment]
> About this click function. As I mentioned above I understand this is a problem. Perhaps this can be fixed somehow. Have to look into that.

Before I changed it to use features, I actually had created my own function for detecting click on routes (LineStrings) - but that was not very precise, it used a bounding box for each route - but maybe I can finetune that!

**Comment by pauldendulk** [comment]
> But apart from all that we now have a new problem. Mapsui comes to a halt if you zoom out on Android with even 10.000 points. This is really really weird since at the start all vertices are already shown.

It is solved by using SKCanvasView instead of SKGLSurfaceView 😢

**Comment by tonyfonager** [comment]
Which is the "slow version" of the two ?

**Comment by pauldendulk** [comment]
SKGLSurfaceView  is supposed to be the fast one. Hardware accelerated. We had reverted from that before because of crashes. SKCanvasView is the older slower one. It seems we have to revert again.

**Comment by tonyfonager** [comment]
Ohhh crap, not good for my 70k points maps ;-)

**Comment by pauldendulk** [comment]
The 'zoom out gets slow' problem is also present in MapView.

**Comment by pauldendulk** [comment]
Well, we have to find another solutions for the 70.000 points anyway. If the vertices keep growing things cannot be solved with faster GPU or CPU.

**Comment by tonyfonager** [comment]
Yes, the 70k is jsut because I have recently started working on my maps - I could end up with much bigger maps.

What I tried first, was to limit the amount of points written to the MemoryLayer, and then having several "route layers".

Lets say we have the 70k points for the route.

Layer 1 (zoom 1->2) : I only draw every 10th points
Layer 2 (zoom 2->3) : I only draw every 9th points
Layer 3 (zoom 3->4) : I only draw every 8th points
....

As I was under the impression, that it only draws the "visible" points on the current zoomed area, my idea was to have the full 70k points only on the higher zoomer levels, and they are all zoomed in - so not many points visible.

It "seemed" to work okay, but it also means that I in total (across the several memorylayers) have more that 70k points.

Not sure if that is a good idea ?

**Comment by tonyfonager** [comment]
But it actually look like if you are already doing something similar ? When I zoom out, my route gets all "jagged" and "spiky", like if you are removing some of the points ?

**Comment by tonyfonager** [comment]
This is the thing I am talking about, where layers are first "redrawn" when I lift the finger from the map (when it moves I keep the finger on the map) :

https://youtu.be/l1cyRQkA3CY

**Comment by pauldendulk** [comment]
>But it actually look like if you are already doing something similar ? When I zoom out, my route gets all "jagged" and "spiky", like if you are removing some of the points ?

We are not removing points. The jaggedness is in the renderer.

**Comment by charlenni** [comment]
We remove points that are outside of the drawing rect. Was a feature, that was added because slow rendering (escpecially when dashed) of big rects on global map.

**Comment by tonyfonager** [comment]
> In Mapsui we draw a feature as a single thing. So all 10.000 vertices. If they were 10.000 points in separate features it would be different. In that case only the visible features will be drawn. So cutting large features up in to smaller is parts could help, and is often a necessity. In my suggestions above perhaps it would be possible to do this cutting up for you.

But will it help to add more features for my routes, when I end up rasterizing the layer anyway ?

**Comment by pauldendulk** [comment]
> This is the thing I am talking about, where layers are first "redrawn" when I lift the finger from the map (when it moves I keep the finger on the map) :

> https://youtu.be/l1cyRQkA3CY

Thanks for the movie. This behavior is by design. The idea was to not do any background work so that map manipulation would be smooth as possible. But this behavior could perhaps be altered or optional. I just rewrote the Delayer to, which is used on the mouse wheel to behave a bit different. We could use the same logic while panning.

There comments here should explain:
https://github.com/Mapsui/Mapsui/blob/eccf73a0d3da63df3ea9e3906769cb0a59e0f694/Mapsui/Fetcher/Delayer.cs#L25-L33

**Comment by pauldendulk** [comment]
>But will it help to add more features for my routes, when I end up rasterizing the layer anyway ?

Did you try it? If you zoom it, it will create a new raster with the features of the more detailed level.

**Comment by tonyfonager** [comment]
> Thanks for the movie. This behavior is by design. The idea was to not do any background work so that map manipulation would be smooth as possible

It makes sense, but if the "pre drawn" are was a bit bigger that the current viewport, it woudl just scroll the data into the visible area ?

In theory, if we "draw" the width x 3 and also the height x 3 to this layer, its not possible to scroll to an area without data.

But, the about means 9 x more drawing, so maybe that just raises a different issue then ?

**Comment by tonyfonager** [comment]
> Did you try it? If you zoom it, it will create a new raster with the features of the more detailed level.

No, but I can definitely try testing it later or tomorrow 👍

**Comment by pauldendulk** [comment]
> In theory, if we "draw" the width x 3 and also the height x 3 to this layer, its not possible to scroll to an area without data.

There are many options to choose from. It is not easy to see the pro's and con's of such optimizations. Making the width and height 3x will also make everything that is drawn 9 times slower. Then there are many different ways the library is used. Using tiling is another way this problem could be handled.

**Comment by pauldendulk** [comment]
> It is solved by using SKCanvasView instead of SKGLSurfaceView 😢

@charlenni This is really disappointing. I could go back to SKCanvasView on Android but not sure if this is a good idea for MapView. We could submit an issue at SkiaSharp but I have had no response at all on my previous two issues.

**Comment by pauldendulk** [comment]
@tonyfonager Perhaps the best option for you is to use the RasterizingLayer for graphics and call MapInfoHelper.GetMapInfo from your own code to get the MapInfo. So you listen to the MapControl.Info event. When you click it will return no MapInfo because of the RasterizingLayer. Then call MapInfoHelper.GetMapInfo with the original layer.

**Comment by charlenni** [comment]
I tried it with a custom style renderer and a prerendered path. Works like a charme on UWP, but has the same problem as before on Android. So I would say, that it is an Android problem. 70000 are a many points.

First of all, before changing anything in Mapsui, I would say, reduce the amount of points. If you recorded the trail with GPS, than there should be many points, that you don't need. If you record all 10 s a point, than your trail is over 194 h long. I assume, that no one walks so long ;-) Than reduce points, that aren't usefull, because they are nearly the same (distance < 1-5 m) or on a line. There are good algorithms for that out there. For example see [here](https://bost.ocks.org/mike/simplify/) or [here](https://de.wikipedia.org/wiki/Douglas-Peucker-Algorithmus).

If you do all the suggested above, than I assume, that your line shouldn't have more than 2000-3000 points. And I'm sure, that Mapsui can handle this, even on older Android devices.

**Comment by tonyfonager** [comment]
> @tonyfonager Perhaps the best option for you is to use the RasterizingLayer for graphics and call MapInfoHelper.GetMapInfo from your own code to get the MapInfo. So you listen to the MapControl.Info event. When you click it will return no MapInfo because of the RasterizingLayer. Then call MapInfoHelper.GetMapInfo with the original layer.

I will try that - thanks for the pointer 👍

**Comment by tonyfonager** [comment]
> If you recorded the trail with GPS, than there should be many points, that you don't need. If you record all 10 s a point, than your trail is over 194 h long. I assume, that no one walks so long ;-) 

I have not recorded the data myself, but I guess you are right - look at this screenshot from my "route editor" - looks like it could be optimized easily:

![image](https://user-images.githubusercontent.com/837894/76152466-4ec8ef00-60c0-11ea-88f8-85a18e4159e7.png)

**Comment by tonyfonager** [comment]
Btw, found this site for optimizing points inside GPX files (which is the file format I use) - looks preeeetty cool from the few minutes I played around with it :

https://labs.easyblog.it/maps/gpx-simplify-optimizer/

**Comment by tonyfonager** [comment]
But again, @charlenni - the above made me think ....

It ofcourse it makes sense to optimize points in routes, if there is "too many" inside the GPX (fx from a self recorded GPS device) - but what if I hit the "upper limit" for Mapsui anyway ?

I have plans of adding some of the biggest routes in the world to my app, and I would believe they are much bigger than the 70k map we are testing today ...

**Comment by charlenni** [comment]
Than you should create more than one LineString. Perhaps one for each resolution/zoom level. For zoom level one you have perhaps 10 points in this feature. In the highest zoom level you could have all points, but only a few are visible on the screen. Try this with the MinZoomVisible/MaxZoomVisible of the layers.

Would it be possible to get such an GPX file?

**Comment by pauldendulk** [comment]
> First of all, before changing anything in Mapsui, I would say, reduce the amount of points. If you recorded the trail with GPS, than there should be many points, that you don't need

Mapsui will always have limits somewhere on what it can handle when using direct draw. There is no way around that. But is not always possible to limit the data. In the majority of apps I worked on the data in the application was not under the control of the developer. It comes from a user's database, requested from a service, or recorded by the user. Mapsui needs to have a solution for this.

**Comment by tonyfonager** [comment]
> Than you should create more than one LineString. Perhaps one for each resolution/zoom level. For zoom level one you have perhaps 10 points in this feature. In the highest zoom level you could have all points, but only a few are visible on the screen. Try this with the MinZoomVisible/MaxZoomVisible of the layers.
> 
> Would it be possible to get such an GPX file?

I alreade created it that way in the current version of my map. I will try it out again, but with rasterrizing layers this time.

**Comment by charlenni** [comment]
And the GPX file?

**Comment by tonyfonager** [comment]
> And the GPX file?

What do you mean ?

**Comment by charlenni** [comment]
I asked, if it would possible to get such a GPX file with so many points to test a little bit.

**Comment by tonyfonager** [comment]
Ohhh sorry, I did not see that sorry.

I can send you the test project I made yesterday, it contains a json file which deserializes into a class with the 70k route of Skåne in Sweden.

Just give me your email and I will send it to you.

**Comment by tonyfonager** [comment]
Just found your email - should I just send a copy to : mail@wfplayer.com ?

**Comment by charlenni** [comment]
I updated my Android device to Android 8 and tried this test with 70.000 points. I haven't any problems. Map moves good, Line isn't draw always complete, because the rendering is aborted because of moving around.

[ManyVerticesTest_Android8.zip](https://github.com/Mapsui/Mapsui/files/4312143/ManyVerticesTest_Android8.zip)

I assume, that it is a problem with your device. Before the Update of my device, the Vulkan test didn't find a GPU, so perhaps it is the same with your device. Which version of Android do you use?

**Comment by tonyfonager** [comment]
I am testing on iOS - and this is also where I see the crashes.

I tested on my Android P20 Lite (Android 9) and I had no issues on that one.

**Comment by charlenni** [comment]
I assume, that your last message belongs to #865? I don't talk about crashes.

About the problems with the ManyVerticesSample: my fault. Thought, the problem is on Android, because Paul always talked about Android. When looking again on the video, I see, that it is a iOS problem.

**Comment by tonyfonager** [comment]
> I assume, that your last message belongs to #865? I don't talk about crashes.

Sorry, yes - so many tickets that I mix them up ;-)

**Comment by pauldendulk** [comment]
@charlenni The crash that I saw was on Android, reported in this issue https://github.com/Mapsui/Mapsui/issues/862. Tony reported on another crash in this issue https://github.com/Mapsui/Mapsui/issues/865

**Comment by charlenni** [comment]
@pauldendulk Did you checked it with the release version too?

**Comment by pauldendulk** [comment]
@charlenni No, I did not. 

My device is two a month old A70 with Android 9. That should not be a problem.

**Comment by charlenni** [comment]
That's not a problem of the age of the device, but if you create a debug or a release version.

**Comment by pauldendulk** [comment]
> @pauldendulk Did you checked it with the release version too?

@charlenni No, I did not.

**Comment by pauldendulk** [comment]
The summary of this long thread:
- It is always possible to use the RasterizingLayer if there are too many vertices to get descent performance.
- To get better performance the GL renderers should be used. There are issues at the moment but they will be solved with the next skiasharp release.
- It is an option to remove some of the vertices. If performance decreases because of the number of vertices this usually means there are more features than can be distinguished, so it is better to remove them. Mapsui currently has no tools to help with this, so the developer should do this themselves.

**Comment by charlenni** [comment]
Btw. I counted yesterday the amount of pathes and points when drawing a tile of a vector map. There are 90 pathes with around 42000 points in my test tile. It needs 20 ms to draw this tile on screen.

Here the problem is, that 70000 points, each time they are drawn, must be converted from Mapsui coordinate system to screen coordinate system, a SKPath must be created and than drawn. This takes very much time.

It should be possible to get much better performance by converting the LineString once to a SKPath and use an user drawn style to bring this path to screen.

**Comment by pauldendulk** [comment]
@charlenni Yes, I totally agree. The question is where do we store those SKPaths and who is responsible for disposing them. Some options:

### Cache for what is currently in use
We could use a central cache. There the question is when to dispose them. We have something like that for images in the skia renderer, the MapRenderer._tileCache.  All tiles are stored in there and removed when not used in the current iteration. 

### Smart cache
The TileLayer.TileCache has a different strategy. It removed tiles when a limit is exceeded. Tiles can be stored over a longer period there, which might be an advantage. Complications are that it could grow too big, too much memory consumption for mobile, or the cache is too small for the tiles in use. Also every tilelayer has it's own cache which could become too much memory for mobile.

### Cache it in feature (or style)
Another strategy is to add it to a cache in the feature itself. So we need to add some Cache field to IFeature. But what if we switch between Skia and WPF (perhaps clean the entire cache). Another issue is that different style have a different SKPath, so actually we should cache for each style-feature combination. Since a style can be used for multiple feature this can not be used to store a specific path. Perhaps there IFeature should have a Dictionary as cache where every key is a style. In this scenario we need to dispose all feature. The disposing is a complication in general.
