### ISSUE TITLE
Symbol size in meters

### ISSUE THREAD

**Issue by ondrasvoboda** [Mapsui/Mapsui#875]
Hi,
I have SVG symbols in the map and I need them to have each different size defined in meters. Is there a way how to do this?
My only idea so far is to have different style for each feature and recalculate SymbolScale each time resolution is changed. Or is there some better solution?
Thanks a lot!

**Comment by pauldendulk** [comment]
In the xaml renderer we implemented an option where the size is set in world units (the units used for the coordinate system), but this is not implemented in skia. See, SymbolStyle.UnitType.WorldUnit. The default is SymbolStyle.UnitType.Pixel. It is one of few things where xaml has something that skia has not.

You can see it in the sample under 'Special' then 'SymbolsInWorldUnits'. The sample file is SymbolsInWorldUnitsSample.cs.

One option is to submit a PR to implement it in skia.

Note though, the the UnitType of the coordinatesystem is not always a meter. Sometimes it is something completely different (as in WGS84), and often is is an approximation of a meter, which varies over the map.

Another option is to use a polygon instead of a symbol.

Another is not to use it, because often it is not a good idea. Could you explain a bit more about your use case?

**Comment by ondrasvoboda** [comment]
I'm developing tree inventory app - so I draw tree positions into the map.

- Basic use case: user choose SVG icon (circle, cross-hair, dot, ...) and its size and all tree positions are being drawn with the same size icon. (this I have already implemented and works fine)

- Advanced use case: user choose SVG icon as above and want its size to reflect crown diameter of each tree, e.g. 15m.

To have UnitType.WorldUnit implemented in skia would be a great option (not sure if I'm able to handle this). Or how about using custom style renderer for this?

**Comment by pauldendulk** [comment]
> Or how about using custom style renderer for this?

ah yes!, I just came back to this issue to mention this. The rendering itself will not be easier for you (just as hard) but perhaps it is easier for you to understand where to make the changes. In a later stage it would perhaps be possible to use this code to implement UnitType.WorldUnit. 

Documentation here: 
https://mapsui.com/documentation/custom-style-renders.html

Take note, the unit in SphericalMercator (this is what the default osm map is using) is not one on one with meters, but varies depending on the location on the globe. It also varies in the vertical and horizontal. A first implementation could just work with SphericalMercator units. A second version could try to calculate correct meters. Perhaps the best approach would be to first transform to WGS84, then use some generic method (you need to google) to calculate the width and height in meters, then transform those back to SphericalMercator.

**Comment by ondrasvoboda** [comment]
OK, thanks for all advices!
