### ISSUE TITLE
Forms :  Blank map on MacOs, Map Over all on WPF (2.0 Rc-2)

### ISSUE THREAD

**Issue by sailman342** [Mapsui/Mapsui#892]
The Map sitting above everything on forms WPF has already been reported.

On MacOS the map is white on some devices.

This seems to be due to a bad handling of the GPU by SkiaSharp on some devices.

A simple workaround is to use SKCanvasView instead of SKGLView in Mapsui MapControl, this solves the problem at I have not noticed any differencein performance.

You can play with this one **it shows a solution to the problem** 

[See MapsuiTest here](https://github.com/sailman342/MapsuiTest)
this is a short demo build with the Mapsui Form sources rc2

Sorry for my poor mastering of GitHub and some abuse of french language but I found this MapsuiTest usefull for investigating your marvelous code :-)

Thanks to the team and take care , Alain

**Comment by TheProme** [comment]
I have the same events inconvinience. Still looking, maybe there is something I've missed

**Comment by charlenni** [comment]
Sorry, but you mentioned more than one issue at a time. It would be useful, if you open one issue for one problem. If not, then then the overview is getting difficult.

**Comment by charlenni** [comment]
@TheProme Which Problem have you too?

**Comment by sailman342** [comment]
@charlenni 

Sorry good point, I left the Blank screen ans Map overAll problem which are tied together because they are due to the SkiaSharp GPU handling. They are  solved by using SKCanvasView instead of SKGlView.

**Comment by sailman342** [comment]
For me the issue is still open, by moving to OpenGL one preclude the usage of Mapsui on non GPU or poor GPU support from SkiaSharp. On desktops, CPU usage is very performent. 

Only a pair of lines of codes are different for both implementations, is it inadeqaute to think both versions could coexists !

**Comment by charlenni** [comment]
@sailman342 I made from your MapsuiTest project a derived [SkiaTest](https://github.com/charlenni/SkiaTest) version with GPU and CPU canvas beside for all platforms. It would be nice, if you could check this version. Perhaps you find the same problems.

Android:
1. Press "Start" button
2. Let it run for a second
3. Press "Stop" button
4. Turn off your device
5. Turn it on again
6. GPU backed canvas is empty, CPU backed canvas is correct

WPF:
1. Background of both canvas aren't correct. Should be dark grey.
2. When setting background by Canvas.Clear() then it is correct
3. Label in the top left corner and button in top right corner aren't visible on GPU side because canvas stays always on top.

iOS:
1. Press "Start" button
2. After some second the CPU canvas stops drawing
3. Touch display and move around
4. Canvas is drawn correct when moving around while touching

MacOS
1. Background of GPU canvas isn't correct
2. When setting background by Canvas.Clear() then it is correct

UWP:
Works perfect ;-)

Btw. my MacOS version doesn't have any problems with this test (except the background) and with Mapsui too.

**Comment by charlenni** [comment]
Regarding your WPF problem: see SkiaSharp [#1108](https://github.com/mono/SkiaSharp/issues/1108).

**Comment by sailman342** [comment]
Testing on Samsung SM-T850 (Tab A 10" 2016) Android 8.1.0 API-27
Testing on Samsung S10 Android 10.0 API-29
Debugger on or off

Press "Start" button
Let it run for a second
Press "Stop" button
Turn off your device
Turn it on again
GPU backed canvas is correct, CPU backed canvas is correct

Additional test
Turning off device while running works fine on S10, restart from where it was

Turning off device while running crashes on Tab A with debugger attached
Turning off device while running works fine on Tab A but start/stop is on stop !

**Comment by charlenni** [comment]
Thank you for your help.

Very strang, because I see it here for my device and both emulators I use.

Do you have a device with 8.0 and below?

**Comment by charlenni** [comment]
Could you reproduce your MacOS problem with SkiaTest? I tried to do this, but couldn't see it with my Mac Mini Late 2012. Works perfect.

**Comment by sailman342** [comment]
Sorry I went  out to listen to our President of the Confederation concerning the confinement here in Switzerland, we have to stay in at least up to june 8th …

I did test on UWP, works like you, on WPF same problems … but I agree this is a known problem.

**Comment by sailman342** [comment]
![test mac](https://user-images.githubusercontent.com/58634016/79468051-c44ca700-7ffe-11ea-9db8-b5d2d287f5db.png)

**Comment by sailman342** [comment]
This is a mid-2011 IMac 27 inch

**Comment by sailman342** [comment]
I rebooted the mac with High Sierra, black screen on start on GPU side, clicking the checkbox and comes back to normal … unclick and black again...

**Comment by sailman342** [comment]
Tested on an old Lenovo Pocket Tablet, Android 7.0 works like a charm …

Can turn off/on while running as well :-)

**Comment by sailman342** [comment]
iOS same as you but starts with GPU black … (iPhone 8 iOS 13.4)

**Comment by charlenni** [comment]
This is, what I get on the Mac Mini
![grafik](https://user-images.githubusercontent.com/4381223/79476362-2ca08600-8009-11ea-8e19-7851302d015a.png)
It seems, that the black background isn't a problem. You only have to use `Canvas.Clear(color)` to set your background color. That is the workaround.

But I don't understand, that the graphics isn't drawn correct. But if you doesn't see anything with this small test app without Mapsui, then it isn't a Mapsui problem. I open a issue on SkiaSharp.

**Comment by charlenni** [comment]
Regarding the WPF problem: Do you see the answer at SkiaSharp #1108?

**Comment by charlenni** [comment]
@sailman342 Perhaps you could write some more to the SkiaSharp bug report for the not drawing Forms.Mac bug at #1235?

**Comment by sailman342** [comment]
You are running Catalina ?

**Comment by charlenni** [comment]
Yes. Cost my 2 days of work. One day of update and finding, why VS 2019 couldn't connect to the Mac anymore and one day of updating XCode (takes over 9 h to update). Than I replaced my harddisc with a SSD. Since than it works a little bit better.

Because I use the Mac sheldom, always I start it, I have to update something. Annoying.

**Comment by sailman342** [comment]
Thanks for your support, but my 2011 Mac is not supported anymore by Apple, if it works with 2012 machines it is perhaps more adequate to focus on the WPF problem as it precludes the use on non Windows 10 PCs and there are still a lot around.

If you like, I can close the issue, but I am always available to help !

You could figure why you have a problem on Android !

> Tested on an old Lenovo Pocket Tablet, Android 7.0 works like a charm …

**Comment by pauldendulk** [comment]
> Yes. Cost me 2 days of work. One day to update and finding, why VS 2019 couldn't connect to the Mac anymore and one day to update XCode (takes over 9 h to update). Than I replaced my harddisc with a SSD. Since than it works a little bit better.
> 
> Because I use the Mac sheldom, always I start it, I have to update something. Annoying.

Very recognizable.
