### ISSUE TITLE
mapsui wpf support for .NET core v3

### ISSUE THREAD

**Issue by lehmannk** [Mapsui/Mapsui#917]
Currently mapsui wpf required .NET 4.6. Would it be possible to provide a port for .NET core v3 for so we can use this great library more platform independent?

**Comment by radderz** [comment]
mapsui is a .net standard implementation so it is platform independent. but each UI platform requires it's own implementation.

If you mean you want a .NET core WPF implementation of the control that's a totally different thing.

**Comment by pauldendulk** [comment]
I assume the purpose is use Mapsui as part of .NET Core 3.0 WPF project. In that case Mapsui.UI.Wpf needs to be compiled as .NET Core 3.0. Currently Mapsui.UI.Wpf is compiled as  .NET Framework 4.6.1. Since we also want to keep supporting .net framework an extra project needs to be added. Perhaps it can share code with the .net framework project. Mapsui.UI.Wpf consists of only a MapControl and some extension methods, 4 files.

![image](https://user-images.githubusercontent.com/963462/82014536-15db6680-967d-11ea-8f3e-858999dd9c75.png)

This is not a lot of work in itself. It is one more thing that we need to support in a growing project that was going slow last year.

**Comment by pauldendulk** [comment]
As a workaround you could copy the 4 files of Mapsui.UI.Wpf into your own .NET Core 3 project. The rest of Mapsui could be added as nuget package. It would be interesting to hear if you need to make any changes to the code.

**Comment by CyLuGh** [comment]
Simply copying those file doesn't seem to be enough. It doesn't seem able to find MouseWheelAnimation or FlingTracker. I didn't have much time to test it further though.

**Comment by pauldendulk** [comment]
@CyLuGh you need to copy those files from the [2.0 branch](https://github.com/Mapsui/Mapsui/tree/2.0). That will resolve the missing MouseWheelAnimation. The FlingTracker is in a shared project. This is a complication. I think you need to copy that as well and perhaps more files from that project. ☹️ I wonder if we should have a shared project here, it looks like this could be in Mapsui core, or in regular Mapsui.Ui project (not shared).

**Comment by RolandKoenig** [comment]
I tried to add .net 5 support using multitargeting on following projects:

- Mapsui.Rendering.Xaml
- Mapsui.Wpf
- Mapsui.Samples.Wpf

It seems to work well.
See my fork: https://github.com/RolandKoenig/Mapsui 

If you are interested, then i could invest further time in testing the following days.

**Comment by pauldendulk** [comment]
Yes, that would be interesting. 

Apparently very few changes are needed in the code. Are there any other issues you run into. What things we need to consider? What could be a disadvantage of supporting this?

The sample project is both net48 and net5.0 (<TargetFrameworks>net48;net5.0-windows</TargetFrameworks>). How to you select which one to run?

**Comment by pauldendulk** [comment]
WPF is now netcoreapp3.1 and net48.
