### ISSUE TITLE
Provide a way to know when panning and zooming happened

### ISSUE THREAD

**Issue by leo-costa** [Mapsui/Mapsui#928]
Hello ! I'm trying to know if there is a way to know if panning or zooming has happened. Currently I have copied the file `Mapsui.UI.Wpf/MapControl.cs` and have added an event on both mouse and manipulation methods. I would rather use what is provided on the Nuget package. Is there any other way ?

Thanks.

**Comment by pauldendulk** [comment]
You can use
```csharp
MapControl.Viewport.ViewportChanged
```

**Comment by leo-costa** [comment]
The problem with using the `ViewportChanged` event is that you can't really tell, without saving those values previous, what changed. Perhaps make the mouse and manipulation methods virtual to allow inheritance ?

**Comment by charlenni** [comment]
That is not correct. ViewportChanged has a PropertyChangedEventArgs as parameter, which has the PropertyName as entry. With this, it should be possible to see, which property of Viewport has changed.

**Comment by leo-costa** [comment]
A simple mouse click on the map, without any panning, has these properties being changed.

* Center
* SetCenter
* Resolution
* SetResolution
* Center
* SetCenter

If I wanted to know the `Center` has changed then the following would need to be done :

1. Save center coords.
2. Every time the PropertyName `Center` has changed save that value.  
3. Figure out if that was the really last time it was fired, because it seems for one mouse click it fires twice.
4. Compare values and do logic.

This seems a little clunky. So for the moment I copied the `MapControl.cs` and introduced an event to suit my need. Does it make sense to expose the touch and mouse methods from MapControls as virtual methods ?

Another unrelated question, I rather ask here then make another issue. Is there an exposed API to know on WPF if the long press / tap and hold was done on the map ? I wish the map info event could be triggered by another mouse button.

**Comment by charlenni** [comment]
Ah, now I see your problem. I added the PropertyChanged event some time (better long time) ago. There I needed informations about the Viewport. But now it doesn‘t work very good. We discuss this already.

I will try to change this in the next week.

@pauldendulk I will try to replace all direct access to the properties by setting functions and at the end create an event with a new EventArgs class, with properties as IsFromAnimation, CenterChanged, ResolutionChanged and so on. Do you think, that this is ok?

**Comment by pauldendulk** [comment]
Not sure yet. Let't think it over a bit longer. You refer to the discussion about every property being set separately. This is something to avoid and we should work on this now that we have improved animation. 

I don't like to add property changes events for all properties. Is that what you had in mind? I was trying to make the viewport simpler actually.

Instead of IsFromAnimation I would prefer ChangeType.Continuous and Discreate which could also be used for dragging (the same applied, you do not do heavy calculations on each change. But this may be separate merge request.

I was also thinking about using a struct for the viewport state, but have not really thought is through.

**Comment by charlenni** [comment]
No, no separate events. But the ViewportChanged event should signal, which property of viewport was changed. A single string as of property name wouldn‘t work. A list is not better. So I thought about flags for each property of viewport (booleans).

**Comment by pauldendulk** [comment]
I am still interested in Viewport updates as a single events, not separate events for separate properties because that causes more screen redraws. With such a setup if would not be easy to see if the Center has changed. The only way to do this is a compare on X and Y values. To make this easier we could also provide the previous Viewport state in the change event.

**Comment by pauldendulk** [comment]
Reading up on this old issue right now. Since the original discussion the Viewport logic has changed. We now use an immutable record which changes as a whole. This reduced the number of redraws, which is good. I am happy this is now done. So, there are no change events for individual properties, and I think there should not be. 

One thing we can do is to add the previous viewport state. It does not look like a big change. This is the current Viewport property.

```csharp
public Viewport Viewport
{
    get => _viewport;
    private set
    {
        if (_viewport == value) return;
        _viewport = value;
        OnViewportChanged();
    }
}
```

**Comment by pauldendulk** [comment]
I created a new [issue](https://github.com/Mapsui/Mapsui/issues/2280).
