### ISSUE TITLE
Tile Overlays

### ISSUE THREAD

**Issue by Kayumiy** [Mapsui/Mapsui#932]
Hello,

I am going to make this view:

![image](https://user-images.githubusercontent.com/22438366/83207126-65498880-a18d-11ea-801d-0efc8705b676.png)

Is it possible to add layer to the map by using Mapsui?

Thank You

**Comment by pauldendulk** [comment]
The Mapsui Map has a Layers list in which various layers can be put over each other. Layer can be of various types and have various sources. It is also possible to create your own data source. So it is possible in at least some way.

What kind of data is the overlay shown in your image?

**Comment by Kayumiy** [comment]
My map data is collection .png images.

**Comment by pauldendulk** [comment]
I see we don't have a sample for this fairly simple case. Perhaps you can draw get something out of the 'Tiles' sample under test. Basically these are just a couple of images that a loaded. This sample is more fancy because they a used within a tileschema. You need to load just one image as a 'Raster' geometry.

What you need to do:
- Add a MemoryLayer
- Create a Raster geometry. It get two parameters:
  - The Boundingbox in sphericalmercator. Perhaps you need to convert those with SphericalMercator.FromLonLat.
  - The data. This is a MemoryStream of the png. You could read the stream from file and put that stream into a MemoryStream.
- Create a Feature and assign the Feature.Geometry with the Raster.

**Comment by pauldendulk** [comment]
@Kayumiy  any progress?

**Comment by JKNAUG** [comment]
I try to achieve a similar thing. The goal is to overlay an image to a certain geographical area, that is rotated, so far I haven't found the right way to do it.

- A raster renders the image just fine and at the right area, but I can't rotate it.
- I managed to show the rotated boundaries of the image using a polygon, but then I fail to display the image within those bounds. 
- With a point (and a SymbolStyle) I was able to display the image and rotate it, but then it doesn't scale with the map zooming

 Any hint on what to use for such a scenario would be greatly appreciated!

**Comment by pauldendulk** [comment]
ah, the source image itself is not rotated. That makes it harder.

What I can think of:
- Rotate the source image before adding it as a Raster type. You could try to use skiasharp for that.
- Create your own custom style renderer. Prettig much everything is possible there. 
  - https://mapsui.com/documentation/custom-style-renders.html

Additional notes: In the WPF renderer we had a point geometry that did scale with the map (UnitType.WorldUnit). This was used for your purpose. This was never implemented in the skiasharp renderer. Also this did not work well because the boundingbox was not taken into account when the image was partially visible, when the central point moved out of view the whole image disappeared. So a better solution would be to add a Rotation to Raster. If this is added we should also take into a account the change in boundingbox of the raster. Like we do with the Viewport.WindowExtend (Quad).

**Comment by JKNAUG** [comment]
@pauldendulk thanks for you help! I ended up using a Raster and rotating the image using SkiaSharp upfront, as you suggested.

Now my remaining problem is an offset, which is likely caused by the fact that my BoundingBox is created from the original image's bounds, not from the rotated one (because I don't get those from my source). 
I tried to use a Quad, rotate it and feed the result of ToBoundingBox() into the raster but that always results in nothing rendering anymore. Here's the relevant portion of the code:

```
var bb = new BoundingBox(SphericalMercator.FromLonLat(lowerLeftLon, lowerLeftLat), SphericalMercator.FromLonLat(upperRightLon, upperRightLat));
Quad qd = new Quad(bb.BottomLeft, bb.TopLeft, bb.TopRight, bb.BottomRight);
Quad rotated = qd.Rotate(Rotation, 0, 0);
this.Raster = new Raster(stream, rotated.ToBoundingBox());
```

Am I using the Quad wrong, or are there any other means to rotate a BoundingBox?

**Comment by pauldendulk** [comment]
Can you make the rotated image itself visible with the regular boundingbox? It will not be in the right position but at least visible. If not something is wrong with the conversion. Perhaps the compression is not supported.

**Comment by JKNAUG** [comment]
Yes, with the regular bounding box it is visible. It's just a little too small, my example rotates by 9 degrees.

**Comment by pauldendulk** [comment]
Okay, so you need to calculate the bigger encapsulating bounding box. I assume you can use the Quad for that somehow, but I can't tell you from memory how to exactly use. How about putting a breakpoint in there to see if the values make sense?

**Comment by WeirdAnakin** [comment]
That's what I already tried, sort of...in my understanding the values were too big, but those were SphericalMercator already and so I can't tell for sure. Then I also wonder why the image didn't render just bigger, instead of not at all. 
I suppose I can try to extend my example code above and transform the resulting BoundingBox back into WGS84 coordinates again, that would allow me to jugde whether they are reasonable or not.

**Comment by JKNAUG** [comment]
Okay, I made this work now. The mistake was in the rotation point coordinates of the quad, which I assumed were relative, but are in fact absolute numbers. So the relevant piece of code now looks as follows:

```
var bb = new BoundingBox(SphericalMercator.FromLonLat(lowerLeftLon, lowerLeftLat), SphericalMercator.FromLonLat(upperRightLon, upperRightLat));
Quad qd = new Quad(bb.BottomLeft, bb.TopLeft, bb.TopRight, bb.BottomRight).Rotate(Rotation, bb.Centroid.X, bb.Centroid.Y);
this.Raster = new Raster(stream, qd.ToBoundingBox());
```

Thanks for your help!

**Comment by pauldendulk** [comment]
ah great! thanks for reporting the solution back on the issue so others can use it.
