### ISSUE TITLE
[Question]How can I change the select resolution to make select a feature easier?

### ISSUE THREAD

**Issue by daxiangxi** [Mapsui/Mapsui#961]
hello, I just use the below code to select a multiline feature:
var infoArgs = _mapControl.GetMapInfo(e.ScreenPosition);
if(infoArgs == null) { return; }
 if (infoArgs.Feature != null)
{
         var currentValue = (bool?)infoArgs.Feature["Selected"] == true;
        infoArgs.Feature["Selected"] = !currentValue; // invert current value
 }

![无标题](https://user-images.githubusercontent.com/5284880/86704306-53d68480-c047-11ea-8eb1-40a2a6392559.png)

the select operation is difficult, if i want to select the feature, i have to touch many times to get it.

Is there any method to make it easier to make the select operation easier?
I know it depends on the viewport's resolution, but i dont know how to modify it.
any help will be appreciated, thank you.

**Comment by pauldendulk** [comment]
Touch detection works by checking the color of the pixel that is clicked. The transparent parts of those images will not respond trigger a click event. A workaround is to give the transparent parts a semi transparent color, and set the transparency high so that it is hard to see. Another is to put another symbol in the background with such a transparency.

There is a todo in the code to allow an option to increase the touch area. It would check a number of pixels in the area of the touch. That would help, but the priority is not high.

**Comment by daxiangxi** [comment]
Thank you pauldendulk, I modifid the code in the MapInfoHelper by set the parameter with viewport.Resolution * 4
public static MapInfo GetMapInfo(IEnumerable<ILayer> layers, IReadOnlyViewport viewport, Point screenPosition,
            ISymbolCache symbolCache, int margin = 0)
        {
            var worldPosition = viewport.ScreenToWorld(screenPosition);
            return GetMapInfo(layers, worldPosition, screenPosition, viewport.Resolution * 4, symbolCache, margin);
        }
the appearance is better now:)
