### ISSUE TITLE
[Question] Adding navigation arrow to map

### ISSUE THREAD

**Issue by TheProme** [Mapsui/Mapsui#963]
Is it possible to create some sort of a navigation arrow on map that points on markers outside visible area using Mapsui? Or any advices on it?
I need some sort of a marker indicator on sides of a visible area. Picture below shows what I intend to do. Red dot represents marker and I need an arrow that points on it.
![WEniFfb](https://user-images.githubusercontent.com/22505666/87129278-b7f08700-c299-11ea-98dd-657ca34f3c6d.jpg)

**Comment by pauldendulk** [comment]
Perhaps the best option is the custom style renderer:
https://mapsui.com/documentation/custom-style-renders.html
It is a bit of work but will give you the most flexibility.

**Comment by TheProme** [comment]
Thanks, I'll give it a try. Also is it possible to get info about objects out of your visible bounding box? Seems like I'd need to gather info about them like that

**Comment by pauldendulk** [comment]
ah yes, that will also be an issue. 

One way is to create your own MemoryProvider (perhaps copy the one in Mapsui) and always return all features instead of filtering.

Another route is to work with features with a bigger extent. In general this is what you want, a features visibility depends on it's style. A wide outline can make it visible outside of it's geometry. A point with a big image as style will be visible while the point itself is outside of the extent. In your case you have a feature that because of it's style is always visible. So it's extent is as wide as the fill extent of the map, or it has an infinite extent. But I don't see yet how we could make that work in Mapsui.

**Comment by TheProme** [comment]
Oh, I got it :) the problem is that I tried to make markers as small as possible because I need click and navigate events on each feature on the map. That's why wide objects are not an option. I'm already facing a problem that one feature style (picture) is too large and I can't click on feature behind that one. And it makes it impossible to select some features

**Comment by pauldendulk** [comment]
The mapinfo event also returns a list of all features touched. Perhaps you could use that. Look at MapInfo.MapInfoRecords. You could present the use with a selection dialog.

**Comment by TheProme** [comment]
That's an interesting one, perhaps I could use that. Thanks a lot :)
