### ISSUE TITLE
Can't enter manipulationdelta event handler in UWP

### ISSUE THREAD

**Issue by jean-gblr** [Mapsui/Mapsui#966]
Hello guys,

So here is the problem i am facing:

I am working on an UWP app and this app is targetted at a windows pc tablet for use with fingers as input devices.

When the use "pinches to zoom" to zoom on the map the map only zooms like on a picture but does not load the next zoom of mbtiles. This behaviour is also valid on the sample.

In order to overcome this behaviour the idea was to implement the same behaviour as when the scroll wheel is used but in the manipulationdelta event handler that does support pinch to zoom.

Now where i am stuck is that when we click(mouse) or touch or pinch (finger) on the map the code never enters the manipulationdelta event handler, THO it enters manipulation started and then completed when input is done.

Does anyone have an idea that could help me what is happening and why I cannot seem to make this work ?

**Comment by arthurjgs** [comment]
(I'm a collaborator on this Issue) However it does work on the Grid (`<Grid ... ManipulationMode="Scale" ManipulationDelta="OnDeltaFuntion">`) but not inside the MapControl scope.

**Comment by pauldendulk** [comment]
Perhaps this is because e.Handle = true is set in the the UWP MapControl.OnManipulationDelete.

You could investigate this by working with a local copy of the Mapsui.UI.Uwp.MapControl. Perhaps you need to copy some dependencies too. 

If you want to update the data while panning you need to call RefreshData(). This call is not done to optimize for responsiveness. Calling RefreshData() will make things slower.

**Comment by jean-gblr** [comment]
Thank you, it did solve our issue :)
