### ISSUE TITLE
when the mapcontrol refreshed, the IterateLayers() function in VisibleFeatureIterator class called twice times

### ISSUE THREAD

**Issue by daxiangxi** [Mapsui/Mapsui#972]
hello, when I touch the mapcontrol and the map refresh,  the IterateLayers() function in VisibleFeatureIterator class called twice times, this will cause the app response slow when the number of features in the map is large. Is it necessary to call this function twice or how can i set the app to call this function only one time？ thank you

**Comment by daxiangxi** [comment]
addtion: I used the writable layer to draw polylines

**Comment by pauldendulk** [comment]
If Map.Refresh() is called internally the RefreshGraphics and RefreshData methods are called. RefreshGraphics triggers a refresh immediately. RefreshData will fetch data from the DataSource, and when this is retrieved it will trigger a map refresh. So, with this story in mind a double refresh makes sense.

From the broader perspective it does not make sense. If data changes a single refresh should be sufficient. I have to think about it.

btw, perhaps you can call RefreshData instead of Refresh.

**Comment by daxiangxi** [comment]
Thanks pauldendulk, actually I didn't call any refresh function myself, I just touched the map and move it, then mapsui refresh data itself, then I traced the code and found the IterateLayers() function in VisibleFeatureIterator class called twice, I think it is not efficiently.
