### ISSUE TITLE
[Bug, Alpha] Current 3.0.0 alpha crashes on start

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#978]
When using Mapsui 3.0.0 (with BruTiles.MbTiles 3.0.0), the app crashes as soon as it tries to load the map, see screenshot. 

![XC7RceEZ](https://user-images.githubusercontent.com/25636075/89957921-f7afe300-dc38-11ea-89f0-05b6704edab1.png)

**Comment by inforithmics** [comment]
I think this is a problem with skiasharp that will probably fixed with version 2.80.2 of libskiasharp. So when this comes out you should reference this in your application and it should work.

issues concerning this:

https://github.com/mono/SkiaSharp/issues/1393
https://github.com/mono/SkiaSharp/issues/1395

**Comment by janusw** [comment]
I'm pretty sure this is fixed by now (via the SkiaSharp update), right? Can we close it?

**Comment by janusw** [comment]
I have not been seeing any startup crashes for a long time. Also: No answer for half a year. Closing.
